Repository dokku/dokku, pull requests merged in 2018-04, with the labels that each got.

#3138 fix: use correct path for /etc/default file
  contrib/dokku-update
  debian/postinst
  dokku
  rpm/dokku.postinst
Labels: type: bug

#3139 feat: add ability to initialize a git repository out of band
  docs/deployment/methods/git.md
  docs/template.html
  plugins/git/commands
  plugins/git/functions
  plugins/git/internal-functions
  plugins/git/subcommands/default
  plugins/git/subcommands/initialize
  plugins/git/subcommands/set
  tests/unit/10_git.bats
Labels: type: enhancement

#3140 feat: add newline to config:get output
  plugins/config/subcommands.go
Labels: type: enhancement

#3095 Migrate env for NGINX_* to PROXY_*
  .stickler.yml
  docs/configuration/domains.md
  docs/configuration/environment-variables.md
  docs/configuration/nginx.md
  docs/configuration/ssl.md
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/post-certs-remove
  plugins/nginx-vhosts/post-certs-update
  plugins/nginx-vhosts/pre-disable-vhost
  plugins/nginx-vhosts/pre-enable-vhost
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/test_helper.bash
Labels: bc-break, status: merge for next minor, type: enhancement

#3107 Remove unused password
  plugins/certs/subcommands/generate
Labels: status: merge for next minor, type: enhancement

#3144 Increase curl max timeout to 600 seconds (10 minutes)
  docs/deployment/methods/buildpacks.md
  docs/getting-started/troubleshooting.md
  plugins/build-env/pre-build-buildpack
  tests/unit/20_build-env.bats
Labels: type: enhancement

#3141 Use apps_exists helper where appropriate
  plugins/apps/functions
  plugins/apps/subcommands/exists
  plugins/git/functions
Labels: type: enhancement

#3151 fix: include missing config/functions source
  plugins/nginx-vhosts/install
Labels: type: bug

#3156 fix: ensure we _always_ include all types in history output
  contrib/release
Labels: type: bug

#3163 Better apt install formatting
  docs/assets/style.css
  docs/home.html
Labels: type: documentation

#3153 Allow specifying a separate DOKKU_HOST_ROOT
  dokku
  plugins/00_dokku-standard/exec-app-json-scripts
  plugins/apps/pre-delete
  plugins/apps/subcommands/clone
  plugins/apps/subcommands/rename
  plugins/common/functions
  plugins/repo/src/subcommands/purge-cache/purge-cache.go
  tests/unit/20_build-env.bats
Labels: needs: tests

#3159 Improve docs for default site with HTTPS
  docs/configuration/domains.md
Labels: type: documentation

#3171 Allow users to override the reported app url
  docs/development/plugin-triggers.md
  plugins/common/functions
Labels: type: enhancement

#3173 fix: do not output error message twice
  plugins/apps/functions
Labels: type: bug

#3175 Implement bash-completion for commands
  contrib/bash-completion
  deb.mk
  dokku
  plugins/common/functions
  plugins/plugin/internal-functions
  plugins/plugin/subcommands/disable
  plugins/plugin/subcommands/enable
  plugins/plugin/subcommands/install
  plugins/plugin/subcommands/uninstall
  plugins/plugin/subcommands/update
  rpm.mk
Labels: type: enhancement

#3176 Detect mixed running status on service start
  plugins/common/functions
  plugins/ps/functions
  plugins/ps/internal-functions
  plugins/ps/subcommands/default
Labels: type: bug

#3177 ensure dokku-redeploy runs when docker is stopped then started
  plugins/00_dokku-standard/install
Labels: type: bug
