Repository dokku/dokku, pull requests merged in 2018-03, with the labels that each got.

#3088 Silence port retrieval stderr
  plugins/network/network.go
Labels: type: bug

#3089 Use a longer password for self-signed certificates
  plugins/certs/subcommands/generate
Labels: type: bug

#3090 Ensure all plugin triggers have docs and events integration
  docs/advanced-usage/event-logs.md
  docs/development/plugin-triggers.md
  plugins/20_events/post-app-clone
  plugins/20_events/post-app-rename
  plugins/20_events/post-extract
  plugins/20_events/pre-start
  plugins/20_events/subcommands/list
  plugins/20_events/uninstall
Labels: type: bug

#3076 Prune worktree after build
  plugins/git/functions
Labels: type: bug

#3091 Properly trigger tar-based deploys on git-deployed repositories
  docs/deployment/application-management.md
  docs/development/plugin-triggers.md
  plugins/20_events/bind-external-ip
  plugins/20_events/deploy-method
  plugins/apps/subcommands/report
  plugins/git/deploy-source
  plugins/git/functions
  plugins/git/receive-app
  plugins/tar/deploy-source
  plugins/tar/functions
  plugins/tar/receive-app
Labels: type: bug

#3092 Add support for configuring the app shell
  docs/configuration/environment-variables.md
  plugins/00_dokku-standard/exec-app-json-scripts
  plugins/enter/subcommands/default
Labels: type: enhancement

#3093 Add subcommands to allow app locking and unlocking
  docs/deployment/application-management.md
  plugins/apps/internal-functions
  plugins/apps/subcommands/lock
  plugins/apps/subcommands/report
  plugins/apps/subcommands/unlock
  plugins/common/functions
  tests/unit/10_apps.bats
Labels: type: enhancement

#2950 Add configuration option to disable automatic app creation
  docs/configuration/environment-variables.md
  plugins/apps/functions
  plugins/common/functions
  plugins/git/functions
  tests/unit/10_apps.bats
Labels: type: enhancement

#3096 docs: Document how to check on a running dokku-installer
  docs/getting-started/installation.md
Labels: type: documentation

#3097 feat: update herokuish to 0.3.35
  deb.mk
Labels: type: enhancement

#3101 Handle stopped nginx during debian installation
  debian/preinst
Labels: type: bug

#3100 Properly handle invalid process type entries during DOKKU_SCALE generation
  plugins/ps/functions
Labels: type: enhancement

#3098 Pull herokuish from docker hub when installing via package
  deb.mk
  rpm.mk
  rpm/herokuish.postinst
Labels: type: enhancement

#3108 Update plugin list output
  docs/advanced-usage/plugin-management.md
Labels: type: documentation

#3106 Remove unnecessary shellcheck disable
  plugins/tar/functions
Labels: type: enhancement

#3105 Follow renaming from deploy-method to deploy-source
  docs/deployment/application-management.md
  plugins/20_events/deploy-source
Labels: type: bug

#3103 Move all vhost related functions to the domains plugin
  plugins/common/functions
  plugins/domains/functions
  plugins/nginx-vhosts/proxy-disable
  plugins/nginx-vhosts/proxy-enable
Labels: type: enhancement, type: refactor

#3104 Add dokku-limit to plugins documentation
  docs/community/plugins.md
Labels: type: documentation

#3110 Upgrade herokuish to 0.3.36
  deb.mk
Labels: type: enhancement

#3112 Minor doc css fixes
  docs/assets/style.css
  docs/community/plugins.md
  docs/deployment/application-deployment.md
  docs/development/plugin-triggers.md
  docs/home.html
  docs/networking/port-management.md
  docs/template.html
Labels: type: documentation

#3111 feat: upgrade herokuish to 0.4.0
  deb.mk
Labels: type: enhancement

#3113 Fix proxy management link
  docs/configuration/domains.md
Labels: type: documentation

#3134 Fix typo in upgrading docs
  docs/getting-started/upgrading.md
Labels: type: documentation

#3135 Revert "Clarify that the checks plugin only matches content start"
  docs/deployment/zero-downtime-deploys.md
Labels: type: documentation

#3114 Enhanced core git plugin
  docs/community/plugins.md
  docs/configuration/environment-variables.md
  docs/deployment/application-deployment.md
  docs/deployment/methods/git.md
  plugins/common/property-functions
  plugins/git/functions
  plugins/git/install
  plugins/git/internal-functions
  plugins/git/post-delete
  plugins/git/subcommands/report
  plugins/git/subcommands/set
  tests/unit/10_git.bats
  tests/unit/20_config.bats
  tests/unit/test_helper.bash
Labels: needs: tests, status: merge for next minor, type: enhancement, type: refactor

#3137 fix: ensure we can disable setting the rev-env-var
  plugins/common/property-functions
  plugins/git/functions
  plugins/git/subcommands/set
  tests/unit/10_git.bats
  tests/unit/test_helper.bash
Labels: type: bug
