Repository dokku/dokku, pull requests merged in 2018-07, with the labels that each got.

#3223 Get the global scheduler if no app is specified
  plugins/ps/subcommands/restore
Labels: type: bug

#3224 feat: allow silencing headers on storage:list output
  plugins/storage/internal-functions
Labels: type: enhancement

#3235 Switch from ps:rebuild to ps:restart
  docs/advanced-usage/persistent-storage.md
Labels: type: documentation

#3234 unset GIT_QUARANTINE_PATH when updating repo submodule
  plugins/git/functions
Labels: type: bug

#3237 feat: support --quiet header when showing all environment variables
  plugins/config/subcommands.go
Labels: type: enhancement

#3238 Handle proxy issues in app renaming
  docs/development/plugin-triggers.md
  plugins/20_events/network-clear-config
  plugins/20_events/proxy-clear-config
  plugins/apps/subcommands/rename
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/proxy-clear-config
  tests/unit/10_apps.bats
  tests/unit/30_core_1.bats
  tests/unit/40_core_2.bats
  tests/unit/test_helper.bash
Labels: type: bug

#3242 feat: upgrade herokuish to 0.4.3
  deb.mk
Labels: type: enhancement
