Repository dokku/dokku, pull requests merged in 2018-12, with the labels that each got.

#3302 Add ability to check on app lock status via apps:locked command
  docs/deployment/application-management.md
  plugins/apps/internal-functions
  plugins/apps/subcommands/lock
  plugins/apps/subcommands/locked
  plugins/apps/subcommands/unlock
  plugins/common/functions
  tests/unit/10_apps.bats
Labels: type: enhancement

#3314 Remove reference to non-existent DigitalOcean hosting plan
  docs/getting-started/advanced-installation.md
Labels: type: documentation

#3312 fix: keep track of failed containers regardless of docker kill output
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: bug

#3324 Add missing source of config functions
  plugins/scheduler-docker-local/internal-functions
Labels: type: bug

#3329 Avoid parsing missing file when retiring containers
  plugins/scheduler-docker-local/scheduler-retire
Labels: type: bug

#3330 Ensure chowned properties always have a user and group set
  plugins/common/properties.go
  plugins/common/property-functions
Labels: type: bug

#3346 feat: always overwrite the dokku.conf file for nginx
  plugins/nginx-vhosts/install
Labels: type: enhancement

#3345 Allow triggering the full report for all apps via --all flag
  plugins/00_dokku-standard/subcommands/report
Labels: type: enhancement

#3344 Allow running dokku report without needing an interactive shell
  plugins/00_dokku-standard/subcommands/report
Labels: type: bug

#3339 Properly check args when calling cleanup globally
  plugins/common/functions
Labels: type: bug

#3348 Use correct name for packagecloud token when running CI commands
  contrib/copy-packages
  contrib/release
  contrib/release-dokku-update
  contrib/release-herokuish
  docs/development/release-process.md
Labels: type: bug

#3353 Normalize tests
  tests/unit/10_apps.bats
  tests/unit/10_certs.bats
  tests/unit/10_checks.bats
  tests/unit/10_git.bats
  tests/unit/10_ps-dockerfile.bats
  tests/unit/10_ps-general.bats
  tests/unit/10_ps-herokuish.bats
  tests/unit/10_repo.bats
  tests/unit/10_tar.bats
  tests/unit/20_build-env.bats
  tests/unit/20_config.bats
  tests/unit/20_docker-options.bats
  tests/unit/20_domains.bats
  tests/unit/20_network.bats
  tests/unit/20_nginx-vhosts_1.bats
  tests/unit/20_storage.bats
  tests/unit/30_client.bats
  tests/unit/30_config-oddities.bats
  tests/unit/30_core_1.bats
  tests/unit/30_events.bats
  tests/unit/30_ssh_keys.bats
  tests/unit/40_core_2.bats
  tests/unit/40_nginx-vhosts_2.bats
  tests/unit/40_plugin.bats
  tests/unit/40_proxy.bats
  tests/unit/40_tags.bats
  tests/unit/test_helper.bash
Labels: type: refactor

#3352 Increase security of default SSL setup
  plugins/nginx-vhosts/install
Labels: bc-break, type: enhancement

#3347 Upgrade herokuish
  deb.mk
Labels: type: enhancement

#3341 Select only default dokku network IP
  plugins/network/network.go
  tests/unit/20_nginx-vhosts_1.bats
  tests/unit/test_helper.bash
Labels: type: bug

#3356 Move storage directory into DOKKU_LIB_ROOT
  plugins/storage/install
Labels: type: bug

#3357 Add support for building arbitrary releases
  .dockerignore
  .gitignore
  contrib/build.Dockerfile
  contrib/herokuish-build.Dockerfile
  contrib/release
  contrib/release-dokku-update
  contrib/release-herokuish
  contrib/update-build.Dockerfile
  deb.mk
  rpm.mk
Labels: type: enhancement

#3349 Ensure apps are cleanly cloned
  docs/development/plugin-triggers.md
  plugins/20_events/post-app-clone-setup
  plugins/apps/subcommands/clone
  plugins/network/.gitignore
  plugins/network/Makefile
  plugins/network/network.go
  plugins/network/src/triggers/post-app-clone-setup/post-app-clone-setup.go
  plugins/nginx-vhosts/post-app-clone-setup
  plugins/scheduler-docker-local/post-app-clone-setup
  tests/unit/10_apps.bats
Labels: type: bug

#3358 Image tag deploy workflow cleanup
  docs/deployment/methods/images.md
  plugins/tags/subcommands/deploy
  plugins/tar/deploy-source
  tests/unit/40_tags.bats
Labels: type: enhancement

#3361 Do not generate dhparam for tests
  plugins/nginx-vhosts/install
  tests/ci/setup.sh
  tests/dhparam.pem
Labels: type: tests

#3366 fix: add post-app-clone-setup to network clean make target
  plugins/network/Makefile
Labels: type: bug

#3368 Balance circleci tests
  .circleci/config.yml
Labels: type: tests

#3367 Run tests from built artifact
  Makefile
  contrib/release-dokku-update
  tests/ci/setup.sh
Labels: type: tests

#3371 Add tests section to changelog
  contrib/release
Labels: type: enhancement

#3369 Pull invalid nginx configuration when the nginx configs fail to validate
  docs/configuration/nginx.md
  docs/deployment/methods/images.md
  docs/deployment/process-management.md
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/subcommands/validate
  plugins/nginx-vhosts/templates/validate.conf.sigil
  tests/unit/40_nginx-vhosts_2.bats
Labels: type: enhancement
