Repository dokku/dokku, pull requests merged in 2019-11, with the labels that each got.

#3784 Ensure checks attempts are tracked per-check instead of globally
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/pre-deploy
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: bug

#3792 Unify property function implementations
  contrib/build-dokku.Dockerfile
  plugins/common/.gitignore
  plugins/common/Makefile
  plugins/common/common.go
  plugins/common/properties.go
  plugins/common/property-functions
  plugins/common/src/prop/prop.go
Labels: type: refactor

#3712 Added new plugin
  docs/community/plugins.md
Labels: type: documentation

#3793 Omit DWARF symbol table and debug information from go binaries
  common.mk
  plugins/common/Makefile
Labels: type: refactor
