Repository dokku/dokku, pull requests merged in 2019-05, with the labels that each got.

#3516 fix nginx template with Connection header to http_connection
  plugins/nginx-vhosts/templates/nginx.conf.sigil
Labels: status: merge for next minor

#3527 Use DOKKU_IMAGE for report command
  dokku
  plugins/00_dokku-standard/subcommands/report
Labels: type: bug

#3528 feat: add support for quiet ps:scale output
  plugins/ps/functions
Labels: type: enhancement

#3530 Updated info about supported Ubuntu versions
  docs/getting-started/installation.md
Labels: type: documentation

#3532 refactor: allow the scheduler to decide if an app is deployed
  docs/development/plugin-triggers.md
  plugins/common/functions
  plugins/scheduler-docker-local/scheduler-is-deployed
Labels: type: refactor

#3535 Add help output for apps:exists
  plugins/apps/internal-functions
Labels: type: documentation

#3536 docs: Add documentation for nginx-pre-reload limitation
  docs/development/plugin-triggers.md
Labels: type: documentation

#3538 feat: silence dokku run 'errors'
  plugins/scheduler-docker-local/scheduler-run
Labels: type: enhancement

#3539 Warn users when ufw is enabled
  contrib/dokku-installer.py
  docs/networking/port-management.md
Labels: type: documentation

#3541 Handle case where image is null on first deploy
  plugins/common/functions
Labels: type: bug

#3523 Add an example how to specify a Dockerfile for deployment
  docs/deployment/methods/dockerfiles.md
Labels: type: documentation

#3517 SSH key updates
  plugins/ssh-keys/functions
  plugins/ssh-keys/subcommands/add
Labels: type: enhancement

#3543 Add ability to clear global domains
  docs/configuration/domains.md
  plugins/domains/functions
  plugins/domains/internal-functions
  tests/unit/20_domains.bats
Labels: type: enhancement

#3547 Correct retrieval of resource values for alternative schedulers
  plugins/resource/resource.go
  plugins/resource/src/triggers/resource-get-property/resource-get-property.go
Labels: type: bug

#3546 feat: add ability to trigger an arbitrary plugin hook
  docs/advanced-usage/plugin-management.md
  plugins/plugin/commands
  plugins/plugin/subcommands/trigger
Labels: type: enhancement

#3548 Remove outdated global resource setting
  docs/advanced-usage/resource-management.md
Labels: type: documentation

#3554 Switch from rawgit to jsdelivr in manifest.json too
  docs/assets/favicons/manifest.json
Labels: type: bug

#3556 Add missing domains:clear-global command
  plugins/domains/subcommands/clear-global
Labels: type: bug

#3549 Add message indicating that the user is looking at default limits/reservations
  docs/advanced-usage/resource-management.md
  plugins/resource/subcommands.go
Labels: type: enhancement

#3557 Standardize on node-js-app in examples
  docs/configuration/domains.md
  docs/configuration/ssl.md
  docs/deployment/zero-downtime-deploys.md
Labels: type: documentation

#3558 Add nginx:show-conf command
  plugins/nginx-vhosts/subcommands/show-conf
Labels: type: enhancement

#3560 Resource setting fixes
  docs/development/plugin-triggers.md
  plugins/app-json/internal-functions
  plugins/common/functions
  plugins/resource/src/triggers/docker-args-process-deploy/docker-args-process-deploy.go
  plugins/resource/subcommands.go
  plugins/scheduler-docker-local/scheduler-run
  tests/unit/20_resource.bats
Labels: type: bug

#3562 Proxy ports manipulation updates
  docs/networking/port-management.md
  plugins/proxy/internal-functions
  plugins/proxy/subcommands/ports-add
  plugins/proxy/subcommands/ports-set
Labels: type: bug, type: documentation

#3561 feat: disable scaling if app contains DOKKU_SCALE file
  docs/development/testing.md
  plugins/common/functions
  plugins/ps/functions
  plugins/ps/internal-functions
  tests/apps/dockerfile-dokku-scale/CHECKS
  tests/apps/dockerfile-dokku-scale/DOKKU_SCALE
  tests/apps/dockerfile-dokku-scale/Dockerfile
  tests/apps/dockerfile-dokku-scale/Procfile
  tests/apps/dockerfile-dokku-scale/check_deploy
  tests/apps/dockerfile-dokku-scale/package.json
  tests/apps/dockerfile-dokku-scale/web.js
  tests/apps/dockerfile-dokku-scale/worker.js
  tests/unit/10_ps-dockerfile.bats
Labels: type: enhancement

#3559 Add trace:on and trace:off
  ISSUE_TEMPLATE.md
  docs/configuration/environment-variables.md
  docs/getting-started/troubleshooting.md
  plugins/trace/commands
  plugins/trace/internal-functions
  plugins/trace/plugin.toml
  plugins/trace/subcommands/default
  plugins/trace/subcommands/off
  plugins/trace/subcommands/on
Labels: status: merge for next minor, type: enhancement

#3540 Do not append the global domain for matching subdomains
  docs/configuration/domains.md
  plugins/domains/functions
  plugins/domains/internal-functions
  tests/unit/20_domains.bats
Labels: bc-break, status: merge for next minor, type: enhancement

#3477 Allow specifying environment variables for dokku run
  docs/deployment/one-off-processes.md
  plugins/00_dokku-standard/commands
  plugins/00_dokku-standard/subcommands/run
  plugins/scheduler-docker-local/scheduler-run
  tests/unit/40_core_2.bats
Labels: type: enhancement

#3564 Add config:clear command
  docs/configuration/environment-variables.md
  plugins/config/config.go
  plugins/config/config_test.go
  plugins/config/functions
  plugins/config/src/commands/commands.go
  plugins/config/src/subcommands/clear/clear.go
  plugins/config/subcommands.go
Labels: type: enhancement

#3563 Properly split strings in sanitized ps:inspect
  plugins/scheduler-docker-local/scheduler-inspect
  tests/unit/10_ps-general.bats
Labels: type: bug

#3565 Properly cleanup temp files
  plugins/app-json/internal-functions
  plugins/certs/subcommands/add
  plugins/certs/subcommands/generate
  plugins/common/functions
  plugins/git/functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/internal-functions
  plugins/ps/functions
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/scheduler-inspect
  plugins/ssh-keys/functions
  plugins/ssh-keys/subcommands/add
  plugins/tar/functions
Labels: type: bug

#3566 Allow users to specify wildcard domains
  plugins/domains/functions
  tests/unit/20_domains.bats
Labels: type: enhancement

#3567 Ignore SC2064
  tests/shellcheck-exclude
Labels: type: bug

#3568 Correct issue with clearing global domains
  plugins/domains/functions
  plugins/domains/subcommands/clear-global
  tests/unit/20_domains.bats
Labels: type: bug

#3574 Add support for pulling app status from scheduler plugins
  plugins/ps/functions
  plugins/scheduler-docker-local/scheduler-app-status
Labels: type: enhancement

#3575 Add a way to cleanup apps for specific schedulers
  plugins/apps/functions
Labels: type: enhancement

#3576 Allow setting DOCKER_BIN path for docker execution
  dokku
  plugins/00_dokku-standard/subcommands/report
  plugins/app-json/internal-functions
  plugins/apps/post-delete
  plugins/apps/pre-delete
  plugins/apps/subcommands/clone
  plugins/apps/subcommands/rename
  plugins/build-env/pre-build-buildpack
  plugins/common/common.go
  plugins/common/functions
  plugins/enter/subcommands/default
  plugins/network/network.go
  plugins/ps/internal-functions
  plugins/ps/subcommands/default
  plugins/repo/src/subcommands/purge-cache/purge-cache.go
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/core-post-deploy
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/post-delete
  plugins/scheduler-docker-local/pre-deploy
  plugins/scheduler-docker-local/pre-restore
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-docker-cleanup
  plugins/scheduler-docker-local/scheduler-inspect
  plugins/scheduler-docker-local/scheduler-logs
  plugins/scheduler-docker-local/scheduler-logs-failed
  plugins/scheduler-docker-local/scheduler-retire
  plugins/scheduler-docker-local/scheduler-run
  plugins/scheduler-docker-local/scheduler-stop
  plugins/scheduler-docker-local/scheduler-tags-create
  plugins/scheduler-docker-local/scheduler-tags-destroy
  plugins/tags/subcommands/default
  tests/unit/20_nginx-vhosts_1.bats
  tests/unit/40_report.bats
Labels: type: enhancement

#3578 Allow omitting resource args by setting DOKKU_OMIT_RESOURCE_ARGS
  plugins/resource/src/triggers/docker-args-process-deploy/docker-args-process-deploy.go
Labels: type: enhancement
