Repository dokku/dokku, pull requests merged in 2019-12, with the labels that each got.

#3798 Fix function descriptions in property-functions file
  plugins/common/property-functions
Labels: type: documentation

#3800 Properly track failed check count
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/pre-deploy
Labels: type: bug

#3801 Update herokuish
  deb.mk
Labels: type: enhancement

#3806 Make default vhost example listen to ipv6
  docs/configuration/domains.md
Labels: type: documentation

#3809 Document nginx:show-conf
  ISSUE_TEMPLATE.md
  docs/configuration/nginx.md
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/subcommands/show-conf
Labels: type: documentation
