Repository dokku/dokku, pull requests merged in 2019-03, with the labels that each got.

#3459 feat: upgrade to herokuish:0.4.9
  deb.mk
Labels: type: enhancement

#3461 feat: allow skipping aws releases for plugins
  contrib/release-plugin
Labels: type: enhancement

#3449 Only override the `WORKDIR` in copy_from_image if the image is `gliderlabs/herokuish` based
  plugins/common/functions
Labels: type: enhancement

#3462 feat: upgrade procfile-util
  Makefile
Labels: type: enhancement

#3463 Implement version flags
  dokku
  plugins/00_dokku-standard/subcommands/version
  tests/unit/10_version.bats
Labels: type: enhancement

#3464 Upgrade to go-procfile-util version 0.6.0
  Makefile
Labels: type: enhancement

#3465 Vagrant VM Enhancements
  Vagrantfile
Labels: type: enhancement

#3467 feat: update golang in use for binary building
  common.mk
Labels: type: enhancement

#3466 Quieter builds
  plugins/app-json/internal-functions
  plugins/checks/install
  plugins/checks/subcommands/disable
  plugins/checks/subcommands/enable
  plugins/checks/subcommands/skip
  plugins/common/functions
  plugins/config/config.go
  plugins/domains/functions
  plugins/git/functions
  plugins/git/install
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/post-certs-update
  plugins/nginx-vhosts/pre-disable-vhost
  plugins/nginx-vhosts/pre-enable-vhost
  plugins/proxy/functions
  plugins/proxy/post-certs-remove
  plugins/proxy/subcommands/disable
  plugins/proxy/subcommands/enable
  plugins/proxy/subcommands/ports-clear
  plugins/proxy/subcommands/set
  plugins/ps/core-post-deploy
  plugins/ps/functions
  plugins/ps/post-stop
Labels: type: enhancement

#3468 Doc cleanup
  docs/advanced-usage/docker-options.md
  docs/advanced-usage/persistent-storage.md
  docs/configuration/domains.md
  docs/configuration/ssl.md
  docs/deployment/application-management.md
  docs/deployment/methods/buildpacks.md
  docs/deployment/zero-downtime-deploys.md
  docs/networking/network.md
  docs/networking/proxy-management.md
Labels: type: documentation

#3470 fix: correct the argument for get_release_cmd
  plugins/app-json/internal-functions
  tests/unit/20_build-env.bats
Labels: type: bug

#3476 Add chrome plugin to documentation
  docs/community/plugins.md
Labels: type: documentation

#3479 Turn off logging for nginx validate configuration
  plugins/nginx-vhosts/templates/validate.conf.sigil
Labels: type: bug
