Repository dokku/dokku, pull requests merged in 2019-04, with the labels that each got.

#3482 rails-database -> railsdatabase
  docs/deployment/application-deployment.md
Labels: type: documentation

#3469 Resource management
  Makefile
  deb.mk
  docs/advanced-usage/resource-management.md
  docs/advanced-usage/schedulers/docker-local.md
  docs/development/plugin-triggers.md
  package.mk
  plugins/app-json/internal-functions
  plugins/buildpacks/plugin.toml
  plugins/common/common.go
  plugins/common/functions
  plugins/common/properties.go
  plugins/network/network.go
  plugins/network/src/triggers/network-compute-ports/network-compute-ports.go
  plugins/network/src/triggers/network-get-ipaddr/network-get-ipaddr.go
  plugins/network/src/triggers/network-get-port/network-get-port.go
  plugins/network/src/triggers/network-write-ipaddr/network-write-ipaddr.go
  plugins/network/src/triggers/network-write-port/network-write-port.go
  plugins/resource/.gitignore
  plugins/resource/Makefile
  plugins/resource/glide.yaml
  plugins/resource/plugin.toml
  plugins/resource/resource.go
  plugins/resource/src/commands/commands.go
  plugins/resource/src/glide.lock
  plugins/resource/src/glide.yaml
  plugins/resource/src/subcommands/limit-clear/limit-clear.go
  plugins/resource/src/subcommands/limit/limit.go
  plugins/resource/src/subcommands/report/report.go
  plugins/resource/src/subcommands/reserve-clear/reserve-clear.go
  plugins/resource/src/subcommands/reserve/reserve.go
  plugins/resource/src/triggers/docker-args-process-deploy/docker-args-process-deploy.go
  plugins/resource/src/triggers/install/install.go
  plugins/resource/src/triggers/post-delete/post-delete.go
  plugins/resource/src/triggers/report/report.go
  plugins/resource/src/triggers/resource-get-property/resource-get-property.go
  plugins/resource/src/vendor/github.com/ryanuber/columnize/.travis.yml
  plugins/resource/src/vendor/github.com/ryanuber/columnize/LICENSE
  plugins/resource/src/vendor/github.com/ryanuber/columnize/README.md
  plugins/resource/src/vendor/github.com/ryanuber/columnize/columnize.go
  plugins/resource/src/vendor/github.com/ryanuber/columnize/columnize_test.go
  plugins/resource/subcommands.go
  plugins/resource/vendor/github.com/ryanuber/columnize/.travis.yml
  plugins/resource/vendor/github.com/ryanuber/columnize/LICENSE
  plugins/resource/vendor/github.com/ryanuber/columnize/README.md
  plugins/resource/vendor/github.com/ryanuber/columnize/columnize.go
  plugins/resource/vendor/github.com/ryanuber/columnize/columnize_test.go
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-run
  rpm.mk
  tests.mk
  tests/unit/10_apps.bats
  tests/unit/20_resource.bats
Labels: type: enhancement

#3485 fix: ensure 'dokku report' always succeeds for any app
  plugins/buildpacks/.gitignore
  plugins/resource/resource.go
  tests/unit/40_report.bats
Labels: type: bug

#3488 fix: call ps:retire from system service
  plugins/scheduler-docker-local/install
Labels: type: bug

#3489 feat: upgrade herokuish to 0.5.0 (Ubuntu 18.04)
  deb.mk
Labels: bc-break, type: enhancement

#3490 Add missing link to resource management docs
  docs/template.html
Labels: type: documentation

#3496 Cleanup glide plugins when running src-clean
  plugins/buildpacks/Makefile
  plugins/config/Makefile
  plugins/network/Makefile
  plugins/repo/Makefile
  plugins/resource/Makefile
Labels: type: enhancement

#3497 Allow reporting domains when there are none specified
  plugins/domains/internal-functions
  tests/unit/20_domains.bats
Labels: type: bug

#3500 Always allow ps:scale proc=0
  plugins/ps/functions
  tests/unit/10_ps-herokuish.bats
Labels: type: bug

#3498 Add ability to report domains globally
  docs/configuration/domains.md
  plugins/domains/internal-functions
  tests/unit/20_domains.bats
Labels: type: enhancement

#3499 Ensure the .buildpacks file exists before writing to it
  plugins/buildpacks/src/triggers/post-extract/post-extract.go
  tests/unit/30_buildpacks.bats
Labels: type: bug

#3501 Move log retrieval to docker-local scheduler
  docs/advanced-usage/schedulers/docker-local.md
  docs/development/plugin-triggers.md
  plugins/common/functions
  plugins/logs/subcommands/default
  plugins/scheduler-docker-local/scheduler-logs
Labels: type: refactor

#3502 Add a trigger to fetch the git revision
  docs/development/plugin-triggers.md
  plugins/git/git-revision
Labels: type: enhancement

#3504 Edits for readability and conciseness
  docs/development/plugin-creation.md
Labels: type: documentation

#3507 Fix GitLab CI examples
  docs/community/tutorials/deploying-with-gitlab-ci.md
Labels: type: documentation

#3510 Remove SPONSORS doc in favor of OpenCollective
  SPONSORS.md
Labels: type: documentation

#3511 Add json output to config:export
  plugins/config/environment.go
  plugins/config/src/commands/commands.go
  plugins/config/src/subcommands/export/export.go
  plugins/config/subcommands.go
  tests/unit/20_config.bats
Labels: type: enhancement

#3513 Support installing plugins via file:// scheme
  plugins/plugin/subcommands/install
  tests/unit/40_plugin.bats
Labels: type: enhancement
