Repository dokku/dokku, pull requests merged in 2019-07, with the labels that each got.

#3603 Drop extra % sign in common.LogVerboseQuiet
  plugins/network/src/triggers/install/install.go
Labels: type: bug

#3605 fix: handle case where there are empty newlines in the authorized_keys file
  plugins/ssh-keys/functions
  tests/unit/30_ssh_keys.bats
Labels: type: bug

#3607 Purge cache using herokuish image
  plugins/apps/pre-delete
  plugins/repo/Makefile
  plugins/repo/repo.go
  plugins/repo/src/subcommands/purge-cache/purge-cache.go
  plugins/repo/src/triggers/pre-delete/pre-delete.go
Labels: type: refactor

#3613 Remove all uses of proxy_set_header Connection "upgrade"
  docs/configuration/ssl.md
  tests/unit/test_helper.bash
Labels: type: documentation

#3610 Correct Bats path in single tests
  tests/bats-exec-test-single
Labels: type: tests

#3614 [config] validate args for config:set and config:unset
  plugins/config/subcommands.go
  tests/unit/20_config.bats
Labels: type: bug

#3612 Improve testing docs
  docs/development/testing.md
Labels: type: documentation

#3618 Ensure the dokku-retire timer is properly installed
  .circleci/config.yml
  plugins/20_events/install
  plugins/common/functions
  plugins/scheduler-docker-local/install
  tests/ci/setup.sh
  tests/unit/30_scheduler-docker-local.bats
Labels: type: bug

#3589 Allow running Dokku in Docker
  .circleci/config.yml
  .dockerignore
  Dockerfile
  contrib/dokku-docker-bin.sh
  contrib/release-dokku
  debian/postinst
  docker/etc/cron.d/dokku-retire
  docker/etc/logrotate.d/services
  docker/etc/my_init.d/10_dokku_init
  docker/etc/runit/runsvdir/default/dokku-restore/finish
  docker/etc/runit/runsvdir/default/dokku-restore/run
  docker/etc/runit/runsvdir/default/nginx/run
  docker/etc/runit/runsvdir/default/rsyslog/run
  docker/etc/sudoers.d/dokku-docker
  docker/usr/local/bin/docker
  docs/getting-started/install/azure.md
  docs/getting-started/install/digitalocean.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/dreamhost.md
  docs/getting-started/install/vagrant.md
  plugins/scheduler-docker-local/check-deploy
  rpm/dokku.postinst
  tests.mk
  tests/ci/setup.sh
Labels: type: enhancement

#3619 Cleanup plugin creation docs
  docs/development/plugin-creation.md
Labels: type: documentation

#3599 Scope docker-cleanup to specific app
  docs/development/plugin-creation.md
  docs/development/plugin-triggers.md
  dokku
  plugins/00_dokku-standard/subcommands/report
  plugins/app-json/internal-functions
  plugins/apps/functions
  plugins/apps/subcommands/clone
  plugins/apps/subcommands/rename
  plugins/build-env/pre-build-buildpack
  plugins/common/functions
  plugins/repo/repo.go
  plugins/scheduler-docker-local/pre-deploy
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-docker-cleanup
  plugins/scheduler-docker-local/scheduler-run
  tests/ci/setup.sh
  tests/unit/40_app-json.bats
Labels: type: enhancement

#3625 Remove old reference to SPONSORS.md
  README.md
Labels: type: documentation
