Repository dokku/dokku, pull requests merged in 2020-04, with the labels that each got.

#3913 Upgrade herokuish
  deb.mk
Labels: type: enhancement

#3914 Add ability to change or disable the access/error log path
  docs/configuration/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/40_nginx-vhosts_2.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#3915 Add ability to check if a plugin has been installed
  docs/advanced-usage/plugin-management.md
  plugins/plugin/internal-functions
  plugins/plugin/subcommands/installed
  tests/unit/40_plugin.bats
Labels: type: enhancement

#3916 Change error exit to warning when no apps exist
  plugins/apps/subcommands.go
  tests/unit/10_apps.bats
Labels: type: bug

#3918 Upgrade herokuish to 0.5.11
  deb.mk
Labels: type: enhancement

#3919 Fix bug with restarting containers not being routed to because of changing IP addresses
  debian/control
Labels: type: bug

#3920 Add the ability to list ssh keys for a specific user
  Makefile
  debian/control
  docs/deployment/user-management.md
  plugins/ssh-keys/subcommands/list
  rpm.mk
  tests/unit/30_ssh_keys.bats
Labels: type: enhancement

#3921 Correct container_type handling when entering containers
  plugins/enter/subcommands/default
Labels: type: bug

#3926 Add proper support for various buildpack urls
  plugins/buildpacks/subcommands.go
  tests/unit/30_buildpacks.bats
Labels: type: enhancement

#3936 Enable limiting and reserving gpu resources
  docs/advanced-usage/resource-management.md
  docs/advanced-usage/schedulers/docker-local.md
  plugins/resource/resource.go
  plugins/resource/src/subcommands/subcommands.go
  plugins/resource/subcommands.go
  plugins/resource/triggers.go
  tests/unit/20_resource.bats
Labels: type: enhancement

#3937 Add minor documentation for the kubernetes and nomad schedulers
  docs/advanced-usage/schedulers/alternate-schedulers.md
  docs/advanced-usage/schedulers/docker-local.md
  docs/template.html
Labels: type: documentation

#3939 Add support for outputting the last visited time
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/internal-functions
Labels: type: enhancement

#3942 Update environment-variables.md
  docs/configuration/environment-variables.md
Labels: type: documentation

#3940 Expose last updated time in git:report
  docs/appendices/0.21.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/git/functions
  plugins/git/git-deploy-branch
  plugins/git/internal-functions
Labels: type: enhancement

#3953 Use correct function name for cmd-tar-in and update migration guide
  docs/appendices/0.20.0-migration-guide.md
  plugins/tar/functions
Labels: type: bug

#3954 feat: upgrade herokuish to 0.5.12
  deb.mk
Labels: type: enhancement

#3957 Add official registry plugin
  docs/community/plugins.md
Labels: type: documentation
