Repository dokku/dokku, pull requests merged in 2020-02, with the labels that each got.

#3838 Expand docs surrounding access control
  docs/deployment/user-management.md
Labels: type: documentation

#3840 Add link to fonts plugin
  docs/community/plugins.md
Labels: type: documentation

#3841 Implement docker-options:clear
  docs/advanced-usage/docker-options.md
  plugins/docker-options/commands
  plugins/docker-options/subcommands/clear
  tests/unit/20_docker-options.bats
Labels: type: enhancement

#3842 rework docker-args-process trigger arguments
  docs/development/plugin-triggers.md
  plugins/app-json/internal-functions
  plugins/builder-dockerfile/builder-build
  plugins/builder-herokuish/builder-build
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-run
Labels: bc-break, type: refactor

#3844 Add global fallback for DOKKU_PROXY_PORT and DOKKU_PROXY_SSL_PORT
  docs/configuration/environment-variables.md
  plugins/nginx-vhosts/functions
  tests/unit/20_nginx-vhosts_1.bats
Labels: type: enhancement

#3843 Enable HSTS by default
  docs/configuration/nginx.md
  docs/configuration/ssl.md
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/hsts.conf.sigil
  tests/apps/multi/app.py
  tests/unit/40_nginx-vhosts_2.bats
Labels: type: enhancement

#3848 Minor logging changes
  plugins/apps/internal-functions
  plugins/apps/subcommands/exists
  plugins/common/functions
  plugins/common/log.go
Labels: type: refactor

#3847 Custom docker networking
  docs/advanced-usage/persistent-storage.md
  docs/deployment/logs.md
  docs/development/plugin-triggers.md
  docs/networking/network.md
  plugins/app-json/internal-functions
  plugins/builder-herokuish/builder-build
  plugins/common/common.go
  plugins/network/.gitignore
  plugins/network/Makefile
  plugins/network/functions.go
  plugins/network/network.go
  plugins/network/src/commands/commands.go
  plugins/network/src/subcommands/subcommands.go
  plugins/network/src/triggers/triggers.go
  plugins/network/subcommands.go
  plugins/network/triggers.go
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-run
  tests/unit/20_network.bats
Labels: type: enhancement

#3849 Reference correct property in network docs example
  docs/networking/network.md
Labels: type: documentation

#3851 Update herokuish to 0.5.6
  deb.mk
Labels: type: enhancement

#3850 DRY up reports in golang
  plugins/buildpacks/buildpacks.go
  plugins/common/common.go
  plugins/network/network.go
  plugins/resource/resource.go
Labels: type: refactor

#3853 Add missing hooks to events plugin
  plugins/20_events/builder-create-dokku-image
  plugins/20_events/builder-dokku-image
  plugins/20_events/post-container-create
  plugins/20_events/scheduler-post-run
Labels: type: bug

#3682 Force tty check to run with the default language
  plugins/common/functions
Labels: type: bug

#3854 Remove deprecated code
  .stickler.yml
  docs/appendices/0.20.0-migration-guide.md
  docs/deployment/zero-downtime-deploys.md
  docs/getting-started/upgrading.md
  plugins/apps/help-functions
  plugins/apps/subcommands/default
  plugins/certs/help-functions
  plugins/certs/internal-functions
  plugins/certs/subcommands/default
  plugins/certs/subcommands/info
  plugins/checks/help-functions
  plugins/checks/subcommands/default
  plugins/docker-options/help-functions
  plugins/docker-options/internal-functions
  plugins/docker-options/subcommands/default
  plugins/domains/help-functions
  plugins/domains/subcommands/default
  plugins/plugin/subcommands/default
  plugins/proxy/help-functions
  plugins/proxy/subcommands/default
  plugins/trace/help-functions
  plugins/trace/subcommands/default
  tests.mk
  tests/unit/10_apps.bats
  tests/unit/10_certs.bats
  tests/unit/10_checks.bats
  tests/unit/20_docker-options.bats
  tests/unit/20_domains.bats
  tests/unit/20_network.bats
  tests/unit/30_client.bats
  tests/unit/30_core_1.bats
  tests/unit/40_core_2.bats
  tests/unit/40_nginx-vhosts_2.bats
  tests/unit/40_plugin.bats
  tests/unit/40_proxy.bats
  tests/unit/40_trace.bats
  tests/unit/test_helper.bash
Labels: bc-break, type: refactor

#3863 Update issue template to remove ambiguity around reporting
  ISSUE_TEMPLATE.md
Labels: type: documentation

#3860 Remove deprecated egrep calls from codebase
  Makefile
  debian/postinst
  plugins/common/functions
  plugins/domains/functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/ps/functions
  plugins/scheduler-docker-local/core-post-deploy
  plugins/scheduler-docker-local/post-delete
  tests.mk
  tests/shellcheck-exclude
  tests/unit/10_ps-dockerfile.bats
  tests/unit/10_ps-herokuish.bats
  tests/unit/20_config.bats
  tests/unit/40_core_2.bats
  tests/unit/40_nginx-vhosts_2.bats
  tests/unit/40_tags.bats
  tests/unit/test_helper.bash
Labels: type: refactor

#3865 Cleanup injected docker labels
  docs/development/plugin-triggers.md
  plugins/builder-dockerfile/builder-release
  plugins/builder-herokuish/builder-release
  plugins/network/subcommands.go
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: refactor

#3868 Remove ps command
  docs/appendices/0.20.0-migration-guide.md
  docs/deployment/process-management.md
  plugins/ps/subcommands/default
  tests/unit/10_ps-dockerfile.bats
  tests/unit/10_ps-general.bats
  tests/unit/10_ps-herokuish.bats
Labels: type: refactor

#3870 Use Println in favor of Fprintln for os.Stdout
  plugins/common/common.go
  plugins/common/log.go
  plugins/common/src/prop/prop.go
  plugins/network/triggers.go
  plugins/resource/triggers.go
Labels: type: refactor

#3869 Standardize plugin trigger calls
  plugins/common/common.go
  plugins/network/network.go
Labels: type: refactor

#3874 Push users to upgrade to recent versions
  ISSUE_TEMPLATE.md
Labels: type: documentation

#3880 Remove unnecessary source/import statements
  plugins/common/functions
  plugins/network/triggers.go
  plugins/nginx-vhosts/core-post-deploy
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/post-app-rename-setup
  plugins/nginx-vhosts/post-domains-update
  plugins/nginx-vhosts/post-proxy-ports-update
  plugins/nginx-vhosts/pre-disable-vhost
  plugins/nginx-vhosts/pre-enable-vhost
  plugins/nginx-vhosts/proxy-build-config
  plugins/nginx-vhosts/proxy-clear-config
  plugins/nginx-vhosts/proxy-disable
  plugins/nginx-vhosts/proxy-enable
  plugins/nginx-vhosts/subcommands/build-config
Labels: type: refactor

#3879 Drop support for unsupported Debian and Ubuntu releases …
  .circleci/config.yml
  README.md
  bootstrap.sh
  contrib/build-base.Dockerfile
  contrib/copy-packages
  contrib/release-dokku
  contrib/release-dokku-update
  contrib/release-herokuish
  deb.mk
  docs/appendices/0.20.0-migration-guide.md
  docs/deployment/methods/dockerfiles.md
  docs/development/testing.md
  docs/getting-started/install/debian.md
  docs/getting-started/install/digitalocean.md
  docs/getting-started/install/dreamhost.md
  docs/getting-started/installation.md
  docs/getting-started/troubleshooting.md
  docs/home.html
  docs/networking/port-management.md
  tests.mk
  tests/ci/setup.sh
Labels: type: refactor
