Repository dokku/dokku, pull requests merged in 2020-08, with the labels that each got.

#4095 Fix application removal during uninstallation
  debian/prerm
Labels: type: bug

#4078 docs: add more details to `nginx-dokku-template-source` trigger
  docs/development/plugin-triggers.md
Labels: type: documentation

#4007 Fix documentation about custom nginx config when using Dockerfile deployment
  docs/configuration/nginx.md
Labels: type: documentation

#4096 Clarify that special config variables are not exposed to applications
  docs/configuration/environment-variables.md
Labels: type: documentation

#4097 Update herokuish
  deb.mk
Labels: type: enhancement

#4100 Fix markdown syntax in nginx docs
  docs/configuration/nginx.md
Labels: type: documentation

#4111 Add large version of dokku image
  docs/assets/dokku-large.png
Labels: type: documentation

#4098 Add a note on how nginx handles load balancing
  docs/deployment/process-management.md
Labels: type: documentation

#4113 Drop herokuish release code
  Makefile
  contrib/build-herokuish.Dockerfile
  contrib/release-herokuish
  deb.mk
  rpm.mk
  tests/ci/setup.sh
Labels: type: refactor

#4116 Ensure config:clear an be called
  plugins/config/Makefile
  tests/unit/config.bats
Labels: needs: tests, type: bug
