Repository dokku/dokku, pull requests merged in 2020-12, with the labels that each got.

#4203 Cleanup log output for failure case
  docs/appendices/0.22.0-migration-guide.md
  plugins/app-json/appjson.go
  plugins/common/functions
  plugins/common/log.go
  tests/unit/config.bats
  tests/unit/storage.bats
Labels: type: enhancement

#4210 Add migration guide link to release notes
  contrib/release-dokku
Labels: type: enhancement

#4211 🐛 Make the dokku-update command compatible with Dokku 0.22+
  contrib/dokku-update
Labels: type: bug

#4212 Cleanup docker options during post-delete
  plugins/docker-options/post-delete
Labels: type: bug

#4213 Enhance the 'plugin' plugin documentation
  docs/advanced-usage/plugin-management.md
Labels: type: documentation

#4214 Expand backup and restore documentation
  docs/advanced-usage/backup-recovery.md
  docs/advanced-usage/plugin-management.md
Labels: type: documentation

#4215 Implement missing cleanup routines
  plugins/docker-options/post-delete
  plugins/nginx-vhosts/post-delete
  plugins/scheduler-docker-local/post-delete
Labels: merge-level: patch, type: bug

#4221 Updating readme for clarity on git push step
  docs/deployment/application-deployment.md
Labels: type: documentation

#4222 Fix typo
  docs/advanced-usage/deployment-tasks.md
Labels: type: documentation

#4225 Accept first pushed branch as deploy-branch
  plugins/git/functions
  plugins/git/internal-functions
  tests.mk
  tests/test_deploy
Labels: type: enhancement

#4234 Switch to bats --filter for running a single test
  docs/development/testing.md
  tests/bats-exec-test-single
Labels: type: documentation

#4236 Remove note regarding not having an official client
  docs/community/clients.md
Labels: type: documentation

#4233 Properly parse releease command when there is an entrypoint
  plugins/app-json/appjson.go
  tests/unit/app-json.bats
  tests/unit/test_helper.bash
Labels: type: bug

#4237 Release dokku-update 0.2.0
  deb.mk
Labels: type: enhancement

#4228 Fix tags:deploy command for images that contain ONBUILD directive
  plugins/builder-dockerfile/builder-release
  tests/unit/tags.bats
Labels: needs: tests, type: bug

#4241 Properly handle stdout when capturing plugn output
  plugins/common/subprocess.go
Labels: type: enhancement

#4220 Update plugn from 0.5.0 to 0.5.1
  Makefile
Labels: type: enhancement

#4218 Enable compilation cache
  common.mk
Labels: type: tests

#4242 Remove reference to 'whitelist'
  plugins/scheduler-docker-local/scheduler-inspect
Labels: type: enhancement

#4239 Ensure all byte output is trimmed of whitespace
  plugins/apps/apps.go
  plugins/apps/functions.go
  plugins/common/common.go
  plugins/common/docker.go
Labels: type: bug

#4238 Ensure dead files are created for docker object retirement
  plugins/scheduler-docker-local/internal-functions
Labels: type: bug

#4243 Do not delete app when the app name is invalid
  plugins/common/common.go
  plugins/common/functions
Labels: type: bug

#4141 feat: always initialize git repository
  plugins/git/functions
  plugins/git/post-create
  tests/unit/git_2.bats
Labels: merge-level: patch, type: enhancement

#4247 Clarify the domain name setting in the docs
  docs/deployment/application-deployment.md
Labels: type: documentation

#4249 Fix typo in zero downtime docs
  docs/deployment/zero-downtime-deploys.md
Labels: type: documentation

#4250 Update upgrading.md
  docs/getting-started/upgrading.md
Labels: type: documentation

#4253 Highlight the default build method used by Dokku
  docs/deployment/application-deployment.md
Labels: type: documentation

#4252 Allow symbolic links for certificate and key files
  plugins/certs/subcommands/add
  tests/unit/certs.bats
Labels: type: bug

#4263 Bump the dokku client formula on release
  .github/workflows/bump-formula.yml
Labels: type: enhancement

#4265 Retry failing and skipped tests once
  .circleci/config.yml
  tests.mk
Labels: type: tests

#4262 Improve ps:restore logging
  plugins/common/parallel.go
  plugins/nginx-vhosts/internal-functions
  plugins/ps/internal-functions
  plugins/ps/ps.go
Labels: type: enhancement

#4261 Add remove by fingerprint and json format output to ssh-keys plugin
  Makefile
  debian/control
  docs/deployment/user-management.md
  plugins/ssh-keys/subcommands/list
  plugins/ssh-keys/subcommands/remove
  rpm.mk
  tests/unit/ssh_keys.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#4266 Update junit test files when a bats retry is successful
  tests.mk
Labels: type: tests

#4264 Correct argument handling when setting the `--app` flag
  contrib/dokku_client.sh
  dokku
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/apps/src/subcommands/subcommands.go
  plugins/apps/subcommands.go
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/buildpacks/subcommands.go
  plugins/common/common.go
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/config/src/subcommands/subcommands.go
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/logs/src/subcommands/subcommands.go
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/network/src/subcommands/subcommands.go
  plugins/network/subcommands.go
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/ps/src/subcommands/subcommands.go
  plugins/ps/subcommands.go
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/repo/src/subcommands/subcommands.go
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/resource/src/subcommands/subcommands.go
  plugins/resource/subcommands.go
  tests/unit/client.bats
Labels: type: bug

#4268 Properly parse flags for logs command
  plugins/logs/src/commands/commands.go
  plugins/logs/subcommands.go
Labels: type: bug

#4269 Rename duplicate test
  tests/unit/app-json.bats
Labels: type: tests

#4270 Allow renaming old applications to new format
  plugins/apps/functions.go
  plugins/apps/subcommands.go
  plugins/apps/triggers.go
  plugins/common/common.go
  plugins/common/functions
  plugins/config/config.go
  plugins/config/environment.go
  plugins/network/go.mod
  tests/unit/apps_1.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#4272 Correct help output for ssh-keys command
  plugins/ssh-keys/help-functions
Labels: type: documentation

#4273 Upgrade to golang 1.15
  common.mk
  plugins/app-json/go.mod
  plugins/apps/go.mod
  plugins/buildpacks/go.mod
  plugins/common/go.mod
  plugins/config/go.mod
  plugins/docker-options/go.mod
  plugins/logs/go.mod
  plugins/network/go.mod
  plugins/nginx-vhosts/go.mod
  plugins/proxy/go.mod
  plugins/ps/go.mod
  plugins/repo/go.mod
  plugins/resource/go.mod
Labels: type: enhancement

#4274 Use correct warning message for deprecated code
  plugins/logs/subcommands.go
Labels: type: bug

#4276 Upgrade version of plugn used in tests
  Makefile
Labels: type: tests

#4275 Add calls to verify app name in subcommands
  docs/development/plugin-triggers.md
  plugins/00_dokku-standard/subcommands/urls
  plugins/apps/functions.go
  plugins/apps/subcommands.go
  plugins/builder-herokuish/pre-build-buildpack
  plugins/buildpacks/subcommands.go
  plugins/certs/functions
  plugins/certs/subcommands/add
  plugins/certs/subcommands/generate
  plugins/certs/subcommands/remove
  plugins/certs/subcommands/show
  plugins/checks/functions
  plugins/common/common.go
  plugins/common/docker.go
  plugins/common/functions
  plugins/config/docker-args-deploy
  plugins/docker-options/subcommands/clear
  plugins/domains/functions
  plugins/domains/subcommands/add
  plugins/domains/subcommands/clear
  plugins/domains/subcommands/disable
  plugins/domains/subcommands/enable
  plugins/domains/subcommands/remove
  plugins/domains/subcommands/set
  plugins/domains/subcommands/setup
  plugins/git/functions
  plugins/git/subcommands/initialize
  plugins/git/subcommands/set
  plugins/logs/subcommands.go
  plugins/network/network.go
  plugins/network/subcommands.go
  plugins/network/triggers.go
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/proxy-disable
  plugins/nginx-vhosts/proxy-enable
  plugins/nginx-vhosts/subcommands/access-logs
  plugins/nginx-vhosts/subcommands/build-config
  plugins/nginx-vhosts/subcommands/set
  plugins/proxy/proxy.go
  plugins/proxy/subcommands.go
  plugins/ps/subcommands.go
  plugins/repo/repo.go
  plugins/repo/subcommands.go
  plugins/resource/subcommands.go
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/subcommands/set
  plugins/storage/internal-functions
  plugins/storage/subcommands/mount
  plugins/storage/subcommands/unmount
  plugins/tags/subcommands/create
  plugins/tags/subcommands/default
  plugins/tags/subcommands/deploy
  plugins/tags/subcommands/destroy
  plugins/tar/functions
  tests/unit/buildpacks.bats
Labels: type: refactor

#4279 Allow vmware-based vm to work on big sur
  Vagrantfile
Labels: type: bug

#4281 Add forum link to documentation
  docs/getting-started/where-to-get-help.md
  docs/home.html
  docs/template.html
Labels: type: documentation

#4282 Cleanup brew-bump integration
  .github/workflows/bump-formula.yml
Labels: type: refactor

#4283 Add CI documentation section for Github Actions and Gitlab
  docs/deployment/continuous-integration/generic.md
  docs/deployment/continuous-integration/github-actions.md
  docs/deployment/continuous-integration/gitlab-ci.md
  docs/template.html
  docs/viewdocs.json
Labels: type: documentation

#4284 Drop old doc link to gitlab ci docs
  docs/template.html
Labels: type: documentation

#4285 Reference official gitlab-ci integration
  docs/deployment/continuous-integration/gitlab-ci.md
Labels: type: documentation
