Repository dokku/dokku, pull requests merged in 2020-05, with the labels that each got.

#3968 Document access.conf issue
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#3970 Clarify the 'see the docs' internal links
  docs/advanced-usage/backup-recovery.md
  docs/configuration/domains.md
  docs/configuration/nginx.md
  docs/configuration/ssl.md
  docs/deployment/application-deployment.md
  docs/deployment/methods/buildpacks.md
  docs/deployment/methods/dockerfiles.md
  docs/deployment/methods/images.md
  docs/networking/proxy-management.md
Labels: type: documentation

#3964 Remove all --force-yes usage throughout the codebase
  contrib/dokku-update
  docs/development/plugin-triggers.md
  docs/getting-started/uninstalling.md
  plugins/nginx-vhosts/dependencies
Labels: type: bug

#3965 Drop dokku references in logging output
  plugins/common/functions
  plugins/ps/functions
Labels: type: enhancement

#3969 Do not logrotate all services files
  docker/etc/logrotate.d/services
Labels: type: bug

#3966 Move domain manipulation into triggers
  docs/development/plugin-triggers.md
  plugins/20_events/domains-add
  plugins/20_events/domains-disable
  plugins/20_events/domains-enable
  plugins/20_events/domains-list
  plugins/20_events/domains-setup
  plugins/20_events/domains-vhost-enabled
  plugins/certs/subcommands/generate
  plugins/common/functions
  plugins/domains/domains-add
  plugins/domains/domains-disable
  plugins/domains/domains-enable
  plugins/domains/domains-list
  plugins/domains/domains-setup
  plugins/domains/domains-vhost-enabled
  plugins/domains/functions
  plugins/nginx-vhosts/core-post-deploy
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/post-domains-update
  plugins/nginx-vhosts/proxy-disable
  plugins/nginx-vhosts/proxy-enable
  plugins/ps/subcommands/restart
Labels: type: enhancement

#3971 feat: allow users to customize the source of the dokku.conf nginx template
  debian/control
  docs/development/plugin-triggers.md
  plugins/20_events/nginx-dokku-template-source
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/templates/dokku.conf.sigil
Labels: type: enhancement

#3977 Set default port for all run commands
  plugins/ps/functions
Labels: type: bug

#3979 Upgrade herokuish
  deb.mk
Labels: type: enhancement

#3980 Clarify that the web installer is not supported in docker-based installs
  docs/getting-started/install/docker.md
Labels: type: documentation

#3982 Allow apps named tls
  docs/appendices/0.21.0-migration-guide.md
  plugins/apps/subcommands.go
  plugins/common/common.go
  plugins/common/functions
Labels: type: enhancement

#3985 Upgrade go-procfile-util to 0.8.2
  Makefile
Labels: type: enhancement

#3986 Upgrade sshcommand to 0.11.0
  Makefile
Labels: type: enhancement

#3987 Upgrade sigil to 0.6.0
  Makefile
Labels: type: enhancement

#3988 Upgrade plugn to 0.5.0
  Makefile
Labels: type: enhancement

#3989 Correct entering running containers
  docs/development/plugin-triggers.md
  plugins/20_events/scheduler-enter
  plugins/common/functions
  plugins/enter/subcommands/default
  plugins/scheduler-docker-local/scheduler-enter
Labels: type: bug

#3967 Add Ubuntu 20.04 support
  bootstrap.sh
  contrib/copy-packages
  contrib/release-dokku
  contrib/release-dokku-update
  contrib/release-herokuish
  docs/getting-started/install/debian.md
  docs/home.html
Labels: type: enhancement

#3996 Clarify network aliases and add section on tld management
  docs/networking/network.md
Labels: type: documentation

#3998 Document the #dokku channel on slack
  docs/getting-started/where-to-get-help.md
Labels: type: documentation

#3999 Update URL for less than 1gb memory in bootstrap.sh [ci skip]
  bootstrap.sh
Labels: type: documentation

#4003 Add dokku.ai asset
  docs/assets/dokku.ai
Labels: type: documentation

#4004 Add support for moby-engine
  debian/control
Labels: type: enhancement
