Repository dokku/dokku, pull requests merged in 2020-03, with the labels that each got.

#3889 Update herokuish
  deb.mk
Labels: type: enhancement

#3888 Mark 9+ for Debian version
  docs/getting-started/installation.md
Labels: type: documentation

#3892 Move code of conduct to .github org repository
  CODE_OF_CONDUCT.md
Labels: type: documentation

#3891 Add missing cpio dependency
  debian/control
  rpm.mk
Labels: type: bug

#3895 Expose network listeners to nginx templates for all process types
  docs/appendices/0.20.0-migration-guide.md
  docs/configuration/nginx.md
  docs/configuration/ssl.md
  docs/development/plugin-triggers.md
  plugins/checks/subcommands/run
  plugins/common/functions
  plugins/network/network.go
  plugins/network/src/triggers/triggers.go
  plugins/network/triggers.go
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  plugins/scheduler-docker-local/scheduler-deploy
  tests/unit/40_nginx-vhosts_2.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#3899 Drop unnecessary quotes on docker inspect calls
  plugins/network/network.go
Labels: type: refactor

#3901 📝 Update information about Dokku CLI installation
  docs/community/clients.md
Labels: type: documentation

#3902 Remove extra commas from network docs
  docs/networking/network.md
Labels: type: documentation

#3907 Add sponsoring link to issue template
  ISSUE_TEMPLATE.md
Labels: type: documentation
