Repository dokku/dokku, pull requests merged in 2020-11, with the labels that each got.

#4181 Conditionally mount the dokku-arch folder if it exists
  Vagrantfile
Labels: type: bug

#4186 Add dokku-discourse to community plugins list
  docs/community/plugins.md
Labels: type: documentation

#4187 Add `-p` flag to "Run on External Volume" tutorial
  docs/community/tutorials/run-on-external-volume.md
Labels: type: documentation

#4183 Embed pb.UnimplementedGreeterServer to avoid linting issues
  tests/apps/gogrpc/greeter_server/main.go
Labels: type: bug

#4188 Added the autosync community plugin
  docs/community/plugins.md
Labels: type: documentation

#4184 Add note regarding using plugin triggers instead of sourcing functions
  docs/development/plugin-creation.md
Labels: type: documentation

#4191 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: type: enhancement

#4194 Drop appName check in apps:report
  plugins/apps/subcommands.go
Labels: type: bug

#4195 Fix whitespace in process-management docs
  docs/deployment/process-management.md
Labels: type: documentation

#4196 Correctly doc apps:report output
  docs/appendices/0.20.0-migration-guide.md
  docs/deployment/application-management.md
  docs/deployment/process-management.md
Labels: type: documentation

#4197 Retire intermediate containers after use
  docs/development/plugin-triggers.md
  plugins/app-json/appjson.go
  plugins/builder-herokuish/builder-build
  plugins/builder-herokuish/builder-release
  plugins/builder-herokuish/pre-build-buildpack
  plugins/common/functions
  plugins/scheduler-docker-local/pre-deploy
  plugins/scheduler-docker-local/scheduler-register-retired
Labels: type: enhancement

#4198 Reference extracted Procfile
  docs/appendices/0.22.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/app-json/appjson.go
  plugins/common/common.go
  plugins/ps/functions.go
  plugins/ps/src/triggers/triggers.go
  plugins/ps/subcommands.go
  plugins/ps/triggers.go
Labels: type: bug

#4202 Schedule related images for cleanup when retiring containers
  docs/development/plugin-triggers.md
  plugins/ps/src/triggers/triggers.go
  plugins/ps/triggers.go
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-register-retired
  plugins/scheduler-docker-local/scheduler-retire
Labels: type: enhancement

#4204 Ensure the image is not an empty string
  plugins/scheduler-docker-local/scheduler-register-retired
Labels: type: bug
