Repository dokku/dokku, pull requests merged in 2020-09, with the labels that each got.

#4115 Add missing labels to built images
  plugins/builder-dockerfile/builder-release
  plugins/builder-herokuish/builder-release
Labels: type: bug

#4123 Support for expected CHECKS text with special characters
  plugins/scheduler-docker-local/check-deploy
Labels: type: bug

#4121 Add ability to disable custom ninx.conf.sigil extraction
  docs/configuration/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  tests/unit/nginx-vhosts_7.bats
Labels: type: enhancement

#4124 Note that docker options require app rebuilds
  docs/advanced-usage/docker-options.md
Labels: type: documentation

#4125 Allow customizing the various nginx templates
  docs/development/plugin-triggers.md
  plugins/20_events/nginx-app-template-source
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/internal-functions
Labels: type: enhancement

#4129 Prohibit non-dns names for apps and process types
  docs/appendices/0.22.0-migration-guide.md
  docs/getting-started/upgrading.md
  plugins/common/common.go
  plugins/common/functions
  plugins/ps/post-extract
  tests/unit/apps_1.bats
Labels: type: enhancement

#4130 Clear proxy configs on boot
  plugins/nginx-vhosts/internal-functions
  plugins/ps/subcommands/restore
Labels: type: bug

#4136 Use git push main:master in docs
  docs/deployment/application-deployment.md
Labels: type: documentation
