Repository dokku/dokku, pull requests merged in 2020-06, with the labels that each got.

#4008 Standardize golang command code
  docs/appendices/0.21.0-migration-guide.md
  docs/deployment/application-management.md
  plugins/apps/functions.go
  plugins/apps/src/subcommands/subcommands.go
  plugins/apps/subcommands.go
  plugins/buildpacks/functions.go
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/buildpacks/subcommands.go
  plugins/common/common.go
  plugins/common/properties.go
  plugins/config/Makefile
  plugins/config/config.go
  plugins/config/src/commands/commands.go
  plugins/config/src/subcommands/subcommands.go
  plugins/config/subcommands.go
  plugins/network/network.go
  plugins/network/src/subcommands/subcommands.go
  plugins/network/subcommands.go
  plugins/proxy/proxy.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
  plugins/repo/src/subcommands/subcommands.go
  plugins/resource/functions.go
  plugins/resource/resource.go
  plugins/resource/src/subcommands/subcommands.go
  plugins/resource/subcommands.go
  tests/unit/20_config.bats
  tests/unit/test_helper.bash
Labels: type: refactor

#4019 Added one possible solution to an error
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#4020 Properly handle multiple containers in ps:inspect
  plugins/scheduler-docker-local/scheduler-inspect
Labels: type: bug

#4021 Depend on python3 binary for CentOS 8 support
  rpm.mk
Labels: type: enhancement

#4025 Switch AUR helper to yay
  contrib/dokku-update
  docs/getting-started/uninstalling.md
  docs/home.html
Labels: type: documentation

#4022 Do not allow slashes in app names
  plugins/common/common.go
  tests/unit/10_apps.bats
Labels: type: bug

#4026 Filter resource args from deploy tasks
  plugins/app-json/internal-functions
Labels: type: bug

#4029 Filter args _after_ docker-args-process-deploy
  plugins/app-json/internal-functions
Labels: type: bug

#4031 Delete old apps and ensure the test helper is quieter
  tests/unit/test_helper.bash
Labels: type: tests

#4034 Teardown apps and containers in global teardown
  tests/unit/test_helper.bash
Labels: type: tests

#4036 Store the deb and rpm artifacts
  .circleci/config.yml
  tests/ci/setup.sh
Labels: type: tests

#4037 Try to output oomkill information
  .circleci/config.yml
Labels: type: tests

#4039 Break out bc-break and refactors in changelog
  contrib/release-dokku
Labels: type: documentation

#4038 Create proxy:build-config command
  docs/appendices/0.21.0-migration-guide.md
  docs/configuration/nginx.md
  docs/networking/proxy-management.md
  plugins/nginx-vhosts/help-functions
  plugins/nginx-vhosts/subcommands/build-config
  plugins/proxy/Makefile
  plugins/proxy/src/commands/commands.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
  tests/unit/test_helper.bash
Labels: type: enhancement
