Repository dokku/dokku, pull requests merged in 2020-01, with the labels that each got.

#3814 Use dokku:report to for listing domains
  docs/configuration/domains.md
Labels: type: documentation

#3818 Add support for host-mode networking
  plugins/network/network.go
  tests/unit/20_network.bats
Labels: type: enhancement

#3828 Reference correct file in nginx:report command
  plugins/nginx-vhosts/subcommands/report
Labels: type: bug
