Repository dokku/dokku, pull requests merged in 2020-07, with the labels that each got.

#4043 Allow controlling nginx proxy-read-timeout
  docs/configuration/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/nginx-vhosts_8.bats
Labels: type: enhancement

#4045 Filter gpus instead of nvidia-gpus from resource arguments
  plugins/app-json/internal-functions
Labels: type: bug

#4046 Make `make test` pass on linting
  plugins/common/functions
  plugins/git/post-app-rename-setup
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/post-app-rename-setup
  plugins/ps/functions
  plugins/scheduler-docker-local/post-app-rename-setup
  tests/unit/test_helper.bash
Labels: type: tests

#4041 feat: Add download option to the certs plugin
  docs/configuration/ssl.md
  plugins/certs/help-functions
  plugins/certs/subcommands/show
  tests/unit/certs.bats
Labels: needs: documentation, type: enhancement

#4055 Delete dokkurc recursively during uninstall
  debian/postrm
Labels: type: bug

#4056 Remove help entry for dokku ps commmand
  plugins/ps/help-functions
Labels: type: documentation

#4058 Ensure web installer creates files with correct permissions
  contrib/dokku-installer.py
Labels: type: bug

#4060 Add warning about the 0.21.0 release
  HISTORY.md
Labels: type: documentation

#4061 Drop go sum and mod files from releases
  common.mk
Labels: type: enhancement

#4040 Added link to the buildpack plugin docs
  docs/deployment/application-deployment.md
Labels: type: documentation

#4063 Clarify why we stop/rebuild apps during upgrade
  docs/getting-started/upgrading.md
Labels: type: documentation

#4064 Use *_PATH consistently
  plugins/domains/functions
  plugins/domains/internal-functions
  plugins/nginx-vhosts/functions
Labels: type: refactor

#4066 add ansible as installation route
  docs/getting-started/installation.md
Labels: type: documentation

#4068 Official plugins are no longer in beta
  docs/community/plugins.md
Labels: type: documentation

#4069 Scheduler plugins are no longer beta
  docs/advanced-usage/schedulers/alternate-schedulers.md
Labels: type: documentation

#4072 Fix deprecation warning in config_all
  plugins/config/functions
Labels: type: bug

#4073 Document the official shell client
  docs/community/clients.md
  docs/deployment/remote-commands.md
Labels: type: documentation

#4074 Force set all plugin permissions on plugin:install/update
  plugins/plugin/install
  plugins/plugin/internal-functions
  plugins/plugin/update
  tests/unit/plugin.bats
Labels: type: bug

#4077 Fix config_all bug introduced in 0.21.2
  plugins/config/functions
Labels: type: bug

#4085 Set warning on resource type as an actual warning
  docs/advanced-usage/resource-management.md
Labels: type: documentation

#4090 Official plugins no longer in beta starting with 0.21.2 release
  docs/community/plugins.md
Labels: type: documentation
