Repository dokku/dokku, pull requests merged in 2021-02, with the labels that each got.

#4366 Update Digitalocean docs
  docs/getting-started/install/digitalocean.md
Labels: type: documentation

#4367 Update deeplink to digitalocean marketplace image on homepage
  docs/home.html
Labels: type: documentation

#4368 Always report resources
  plugins/common/properties.go
Labels: type: bug

#4369 Allow formatting :report command output as json
  plugins/00_dokku-standard/subcommands/report
  plugins/apps/report.go
  plugins/apps/src/subcommands/subcommands.go
  plugins/apps/src/triggers/triggers.go
  plugins/apps/subcommands.go
  plugins/buildpacks/report.go
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/buildpacks/src/triggers/triggers.go
  plugins/buildpacks/subcommands.go
  plugins/common/common.go
  plugins/cron/report.go
  plugins/cron/src/subcommands/subcommands.go
  plugins/cron/src/triggers/triggers.go
  plugins/cron/subcommands.go
  plugins/logs/report.go
  plugins/logs/src/subcommands/subcommands.go
  plugins/logs/src/triggers/triggers.go
  plugins/logs/subcommands.go
  plugins/network/report.go
  plugins/network/src/subcommands/subcommands.go
  plugins/network/src/triggers/triggers.go
  plugins/network/subcommands.go
  plugins/proxy/report.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/src/triggers/triggers.go
  plugins/proxy/subcommands.go
  plugins/ps/report.go
  plugins/ps/src/subcommands/subcommands.go
  plugins/ps/src/triggers/triggers.go
  plugins/ps/subcommands.go
  plugins/resource/resource.go
  plugins/resource/src/subcommands/subcommands.go
  plugins/resource/src/triggers/triggers.go
  plugins/resource/subcommands.go
Labels: type: enhancement

#4377 Add note about the dokku user cron being overwritten by Dokku
  docs/appendices/0.23.0-migration-guide.md
  docs/processes/scheduled-cron-tasks.md
Labels: type: documentation

#4373 Do not attempt to extract Procfile in ps:scale
  plugins/ps/.gitignore
  plugins/ps/subcommands.go
Labels: merge-level: patch, type: refactor

#4386 Update to docker-image-labeler that handles in-use images
  Makefile
  debian/control
  rpm.mk
Labels: merge-level: patch, type: bug

#4384 Add support for injected cron entries from external plugins
  docs/development/plugin-triggers.md
  plugins/20_events/cron-entries
  plugins/20_events/cron-write
  plugins/cron/.gitignore
  plugins/cron/Makefile
  plugins/cron/functions.go
  plugins/cron/src/triggers/triggers.go
  plugins/cron/templates/cron.tmpl
  plugins/cron/triggers.go
  tests/unit/cron.bats
Labels: merge-level: patch, type: enhancement

#4372 Add ability to clear an individual resource
  docs/advanced-usage/resource-management.md
  plugins/resource/functions.go
  tests/unit/resource_1.bats
  tests/unit/resource_2.bats
Labels: merge-level: patch, needs: tests, type: enhancement

#3757 Add provision line to Windows Vagrant box for dokku-installer
  Vagrantfile
Labels: merge-level: patch

#4387 Only warn if the vector container is stopped when fetching logs
  plugins/logs/subcommands.go
  tests/unit/logs.bats
Labels: merge-level: patch, type: enhancement

#4388 Do not inject max-size option when not using local or json-file log-drivers
  docs/appendices/0.23.0-migration-guide.md
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/logs/triggers.go
  tests/unit/cron.bats
  tests/unit/logs.bats
Labels: type: bug

#4394 Swap order of arguments on config-get call
  plugins/app-json/functions.go
Labels: type: bug

#4393 Use docker-image-labeler in cnb builder-build trigger
  plugins/builder-cnb/builder-build
Labels: type: refactor

#4395 Add environment variable support to CNB-based containers
  plugins/builder-herokuish/builder-build
  plugins/config/docker-args-deploy
  plugins/config/environment.go
  plugins/config/environment_test.go
  plugins/config/src/subcommands/subcommands.go
  plugins/config/subcommands.go
  plugins/logs/triggers.go
  plugins/scheduler-docker-local/scheduler-deploy
  tests/apps/python/web.py
  tests/unit/docker-options.bats
  tests/unit/logs.bats
  tests/unit/ps-cnb.bats
  tests/unit/ps-herokuish-1.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#4396 Invalid link to Herokuish Buildpack Deployment in Cloud Native Buildpacks
  docs/deployment/methods/cloud-native-buildpacks.md
Labels: type: documentation

#4397 Correctly handle environment variables in deployment tasks for Cloud Native Buildpacks
  docs/development/plugin-triggers.md
  plugins/20_events/config-export
  plugins/app-json/functions.go
  plugins/common/docker.go
  plugins/common/functions
  plugins/config/Makefile
  plugins/config/functions.go
  plugins/config/src/triggers/triggers.go
  plugins/config/subcommands.go
  plugins/config/triggers.go
  plugins/scheduler-docker-local/scheduler-deploy
  tests/apps/python/Procfile
  tests/apps/python/release.py
  tests/apps/python/requirements.txt
  tests/unit/app-json.bats
Labels: type: bug

#4399 Drop extra log output in cron plugin
  plugins/cron/functions.go
Labels: type: bug

#4402 fix: correctly handle is-deployed check
  docs/development/plugin-triggers.md
  plugins/app-json/go.sum
  plugins/common/Makefile
  plugins/common/common.go
  plugins/common/functions
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/common/src/common/common.go
  plugins/common/src/triggers/triggers.go
  plugins/common/triggers.go
  tests/apps/python-console-only/Procfile
  tests/apps/python-console-only/console.py
  tests/apps/python-console-only/null
  tests/unit/ps-general.bats
Labels: type: bug

#4403 Llint files during CI
  .circleci/config.yml
  .codacy.yml
  .github/linters/.markdown-lint.yml
  .github/linters/.yamllint.yml
  .github/workflows/bump-formula.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  Dockerfile
  README.md
  plugins/20_events/help-functions
  plugins/builder-cnb/builder-build
  plugins/certs/help-functions
  plugins/checks/help-functions
  plugins/common/functions
  plugins/docker-options/functions
  plugins/docker-options/help-functions
  plugins/domains/functions
  plugins/domains/help-functions
  plugins/enter/help-functions
  plugins/git/help-functions
  plugins/git/internal-functions
  plugins/nginx-vhosts/help-functions
  plugins/plugin/help-functions
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/help-functions
  plugins/scheduler-docker-local/pre-deploy
  plugins/shell/help-functions
  plugins/ssh-keys/help-functions
  plugins/storage/help-functions
  plugins/tags/help-functions
  plugins/tar/help-functions
  plugins/trace/help-functions
  tests/apps/.websocket.disabled/check_deploy
  tests/apps/dockerfile-entrypoint/entrypoint
  tests/ci/setup.sh
  tests/unit/core_2.bats
  tests/unit/test_helper.bash
Labels: type: tests

#4406 Fix typo in error message
  plugins/logs/set.go
Labels: type: bug

#4404 Add ability to trigger release via github actions
  .github/workflows/release.yml
Labels: type: enhancement

#4411 Replace nginx:build-config => proxy:build-config
  docs/configuration/nginx.md
Labels: type: documentation

#4412 Fix generation of crontab
  plugins/cron/functions.go
Labels: type: bug

#4413 Fix SSL documentation link in troubleshooting docs
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#4414 Use correct html for offsite digitalocean link
  docs/home.html
Labels: type: documentation

#4417 Correct vector sink example command
  docs/deployment/logs.md
Labels: type: documentation

#4418 Drop unused skip-restart flag for proxy:disable
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
Labels: merge-level: patch

#4420 Add ability to specify X-Forwarded-Ssl header for proxied requests
  docs/configuration/ssl.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/nginx-vhosts_6.bats
Labels: merge-level: patch, type: enhancement

#4422 Add warning regarding shallow clone pushes
  docs/deployment/methods/git.md
Labels: type: documentation

#4421 Keep the git directory for worktree-enabled installations
  docs/deployment/methods/git.md
  plugins/git/functions
  plugins/git/internal-functions
  tests/unit/git_1.bats
Labels: merge-level: patch, type: bug

#4423 Drop unused sigil packaging code
  contrib/build-dokku.Dockerfile
  deb.mk
  rpm.mk
  tests/ci/setup.sh
Labels: merge-level: patch

#4427 Change process management doc references to make more sense
  docs/processes/process-management.md
  docs/template.html
Labels: type: documentation

#4428 Bump azure ARM quickstart template on release
  .github/commands/bump-azure
  .github/workflows/bump-azure.yml
Labels: merge-level: patch, type: enhancement

#4435 Change page title based on current page
  docs/template.html
Labels: type: documentation

#4436 Properly handle directory change when cleaning .git directory
  plugins/git/internal-functions
Labels: merge-level: patch, type: bug

#4437 Switch to using GIT_DIR environment variable to fix Centos 7 support
  plugins/certs/post-app-clone-setup
  plugins/domains/post-app-clone-setup
  plugins/git/internal-functions
  plugins/nginx-vhosts/post-app-clone-setup
  plugins/scheduler-docker-local/post-app-clone-setup
  plugins/scheduler-docker-local/post-app-rename-setup
Labels: merge-level: patch, type: bug

#4439 View Doc redirect not working. Change to use direct link
  docs/configuration/nginx.md
Labels: type: documentation

#4444 Uuse updated links for documentation
  CONTRIBUTING.md
  HISTORY.md
  ISSUE_TEMPLATE.md
  README.md
  bootstrap.sh
  contrib/dokku-installer.py
  docs/advanced-usage/backup-recovery.md
  docs/advanced-usage/docker-options.md
  docs/advanced-usage/persistent-storage.md
  docs/appendices/0.5.0-migration-guide.md
  docs/appendices/0.6.0-migration-guide.md
  docs/appendices/0.7.0-migration-guide.md
  docs/configuration/environment-variables.md
  docs/configuration/ssl.md
  docs/deployment/application-deployment.md
  docs/deployment/methods/herokuish-buildpacks.md
  docs/deployment/methods/images.md
  docs/deployment/zero-downtime-deploys.md
  docs/getting-started/where-to-get-help.md
  docs/networking/port-management.md
  docs/template.html
  plugins/scheduler-docker-local/pre-deploy
  tests/apps/dockerfile/app.json
  tests/apps/go-fail-postdeploy/app.json
  tests/apps/go-fail-predeploy/app.json
  tests/apps/nodejs-express/app.json
Labels: type: documentation

#4445 Bump azure template and formula directly on release
  .github/workflows/bump-azure.yml
  .github/workflows/bump-formula.yml
  .github/workflows/release.yml
  contrib/release-dokku
Labels: type: refactor

#4447 Checkout code to ensure the bump-azure script is available
  .github/workflows/release.yml
Labels: type: bug

#4448 Add documentation for git push to dokku-in-docker
  docs/getting-started/install/docker.md
Labels: type: documentation

#4419 Add parallelism to certain proxy commands
  docs/appendices/0.24.0-migration-guide.md
  docs/networking/proxy-management.md
  plugins/proxy/functions.go
  plugins/proxy/proxy.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
Labels: merge-level: minor, type: enhancement

#4424 Implement git:auth command
  .github/workflows/ci.yml
  Makefile
  debian/control
  docs/deployment/methods/git.md
  plugins/git/help-functions
  plugins/git/internal-functions
  plugins/git/subcommands/auth
  rpm.mk
  tests/ci/setup.sh
  tests/unit/git_3.bats
Labels: merge-level: minor, type: enhancement

#4425 Implement heroku's postdeploy deployment task
  docs/advanced-usage/deployment-tasks.md
  plugins/app-json/appjson.go
  plugins/app-json/functions.go
  plugins/app-json/triggers.go
  tests/unit/app-json.bats
  tests/unit/test_helper.bash
Labels: merge-level: minor, plugin: app-json, type: enhancement

#4374 Change exit code when app does not exist
  plugins/app-json/functions.go
  plugins/app-json/src/triggers/triggers.go
  plugins/apps/src/subcommands/subcommands.go
  plugins/apps/src/triggers/triggers.go
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/buildpacks/src/triggers/triggers.go
  plugins/common/common.go
  plugins/common/functions
  plugins/common/log.go
  plugins/common/properties.go
  plugins/config/config.go
  plugins/config/environment.go
  plugins/config/src/commands/commands.go
  plugins/config/src/subcommands/subcommands.go
  plugins/config/src/triggers/triggers.go
  plugins/cron/src/subcommands/subcommands.go
  plugins/cron/src/triggers/triggers.go
  plugins/logs/src/commands/commands.go
  plugins/logs/src/subcommands/subcommands.go
  plugins/logs/src/triggers/triggers.go
  plugins/network/functions.go
  plugins/network/src/subcommands/subcommands.go
  plugins/network/src/triggers/triggers.go
  plugins/network/subcommands.go
  plugins/network/triggers.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/src/triggers/triggers.go
  plugins/ps/src/subcommands/subcommands.go
  plugins/ps/src/triggers/triggers.go
  plugins/repo/src/subcommands/subcommands.go
  plugins/repo/src/triggers/triggers.go
  plugins/resource/src/subcommands/subcommands.go
  plugins/resource/src/triggers/triggers.go
Labels: merge-level: minor, type: refactor
