Repository dokku/dokku, pull requests merged in 2021-01, with the labels that each got.

#4290 Add support for debug logging plugin trigger stderr and stdout
  plugins/common/common.go
  plugins/common/log.go
  plugins/common/subprocess.go
Labels: type: enhancement, type: refactor

#4289 Clean precheck tmp file on exit
  plugins/scheduler-docker-local/pre-deploy
Labels: type: enhancement

#4288 Add the pid of the dokku process to event logs
  plugins/common/functions
Labels: type: enhancement

#4287 Refactor parallelized goroutines to use error groups
  plugins/app-json/appjson.go
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.sum
  plugins/buildpacks/go.sum
  plugins/common/common.go
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.sum
  plugins/logs/go.sum
  plugins/network/go.sum
  plugins/proxy/go.sum
  plugins/ps/go.sum
  plugins/repo/go.sum
  plugins/resource/go.sum
Labels: type: refactor

#4293 Fix path in persistent storage docs
  docs/advanced-usage/persistent-storage.md
Labels: type: documentation

#4292 Update docs to note support for Ubuntu 20.04
  docs/getting-started/installation.md
Labels: type: documentation

#4291 Add log aggregation support via Vector
  Dockerfile
  docs/configuration/environment-variables.md
  docs/deployment/logs.md
  dokku
  plugins/common/docker.go
  plugins/common/log.go
  plugins/common/properties.go
  plugins/logs/.gitignore
  plugins/logs/Makefile
  plugins/logs/functions.go
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/logs/logs.go
  plugins/logs/report.go
  plugins/logs/src/commands/commands.go
  plugins/logs/src/subcommands/subcommands.go
  plugins/logs/src/triggers/triggers.go
  plugins/logs/subcommands.go
  plugins/logs/triggers.go
  plugins/network/network.go
  plugins/network/subcommands.go
  plugins/ps/ps.go
  plugins/ps/subcommands.go
Labels: type: enhancement

#4294 Enhance ssh client logging output
  contrib/dokku_client.sh
Labels: type: enhancement

#4286 Add support for templated CHECKS files
  docs/deployment/zero-downtime-deploys.md
  plugins/scheduler-docker-local/check-deploy
  tests/apps/nodejs-express/web.js
  tests/unit/checks.bats
  tests/unit/test_helper.bash
Labels: type: enhancement

#4295 Update ps subcommands and triggers
  plugins/ps/Makefile
Labels: type: bug

#4301 Ensure vector container starts correctly
  docs/deployment/logs.md
  plugins/apps/report.go
  plugins/apps/src/subcommands/subcommands.go
  plugins/buildpacks/report.go
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/common/common.go
  plugins/common/docker.go
  plugins/common/log.go
  plugins/logs/functions.go
  plugins/logs/report.go
  plugins/logs/src/commands/commands.go
  plugins/logs/src/subcommands/subcommands.go
  plugins/logs/subcommands.go
  plugins/network/report.go
  plugins/network/src/subcommands/subcommands.go
  plugins/proxy/report.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/ps/report.go
  plugins/ps/src/subcommands/subcommands.go
  plugins/resource/resource.go
  plugins/resource/src/subcommands/subcommands.go
  tests/unit/logs.bats
  tests/unit/test_helper.bash
Labels: type: bug

#4307 Specify that the dokku logo is for non-commercial use
  CONTRIBUTING.md
Labels: type: documentation

#4309 Correct issue where verifying an app name would bail early
  plugins/common/functions
Labels: type: bug

#4319 Update ruby dependencies in test app
  tests/apps/ruby/Gemfile
  tests/apps/ruby/Gemfile.lock
Labels: dependencies, ruby

#4320 Hardcode cnb workdir to /workspace
  plugins/common/functions
  plugins/scheduler-docker-local/scheduler-enter
Labels: type: bug

#4321 Add git version to output
  plugins/00_dokku-standard/subcommands/report
Labels: type: enhancement

#4323 Fix typo in nginx documentation
  docs/configuration/nginx.md
Labels: type: documentation

#4311 Allow named volume mounts in regex
  plugins/storage/functions
  tests/unit/storage.bats
Labels: needs: tests, type: bug

#4330 Switch to using uuidgen for unique app names
  tests/unit/test_helper.bash
Labels: type: tests

#4332 Correct aws release check in release-plugin script
  contrib/release-plugin
Labels: type: bug

#4338 Strip trailing slashes in hostname from web installer
  contrib/dokku-installer.py
Labels: merge-level: patch, type: bug

#4331 Switch to upstream bats-core
  Makefile
  tests.mk
Labels: merge-level: patch, type: tests

#4329 Standardize apt-get usage
  Dockerfile
  Makefile
  Vagrantfile
  bootstrap.sh
  contrib/build-base.Dockerfile
  contrib/build-dokku-update.Dockerfile
  contrib/build-dokku.Dockerfile
  contrib/packer.json
  deb.mk
  docs/development/plugin-triggers.md
  docs/getting-started/install/debian.md
  docs/getting-started/upgrading.md
  plugins/nginx-vhosts/dependencies
  rpm.mk
  tests.mk
  tests/ci/setup.sh
Labels: merge-level: patch, type: refactor

#4335 Add error checking to plugin:install and plugin:update
  plugins/plugin/internal-functions
  plugins/plugin/subcommands/install
  plugins/plugin/subcommands/update
  tests/unit/plugin.bats
Labels: merge-level: patch, type: bug

#4334 allow git pushes to apps that already exist but have old names
  plugins/git/functions
Labels: merge-level: patch, type: bug

#4341 Add testing link to contributing.md
  CONTRIBUTING.md
Labels: type: documentation

#4342 point to current testing docs
  CONTRIBUTING.md
Labels: type: documentation

#4340 Allow configuring x-forwarded-* proxy headers via nginx:set
  docs/configuration/ssl.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/nginx-vhosts_6.bats
Labels: merge-level: minor, type: enhancement

#4333 Drop tmpdir environment variables when not running as dokku user
  dokku
Labels: merge-level: minor, type: bug

#4297 Add support for cloning/syncing from a remote repository
  docs/deployment/methods/git.md
  plugins/git/functions
  plugins/git/help-functions
  plugins/git/install
  plugins/git/internal-functions
  plugins/git/post-app-clone-setup
  plugins/git/post-app-rename-setup
  plugins/git/post-create
  plugins/git/post-delete
  plugins/git/receive-app
  plugins/git/subcommands/allow-host
  plugins/git/subcommands/initialize
  plugins/git/subcommands/public-key
  plugins/git/subcommands/sync
  tests/unit/git_1.bats
  tests/unit/git_3.bats
Labels: merge-level: minor, needs: tests, type: enhancement

#4343 feat: add initial scheduled task implementation
  docs/deployment/one-off-processes.md
  docs/processes/entering-containers.md
  docs/processes/one-off-tasks.md
  docs/processes/process-management.md
  docs/processes/scheduled-cron-tasks.md
  docs/template.html
  docs/viewdocs.json
  plugins/00_dokku-standard/subcommands/run
  plugins/app-json/.gitignore
  plugins/app-json/Makefile
  plugins/app-json/appjson.go
  plugins/app-json/functions.go
  plugins/app-json/triggers.go
  plugins/buildpacks/report.go
  plugins/cron/.gitignore
  plugins/cron/Makefile
  plugins/cron/functions.go
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/cron/plugin.toml
  plugins/cron/report.go
  plugins/cron/src/commands/commands.go
  plugins/cron/src/subcommands/subcommands.go
  plugins/cron/src/triggers/triggers.go
  plugins/cron/subcommands.go
  plugins/cron/templates/cron.tmpl
  plugins/cron/triggers.go
  plugins/network/report.go
  plugins/proxy/report.go
  plugins/resource/resource.go
  plugins/scheduler-docker-local/scheduler-run
  tests/apps/python/task.py
  tests/unit/cron.bats
  tests/unit/init.bats
Labels: type: enhancement

#4318 Add ability to set client max body size via nginx:set
  docs/configuration/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  tests/unit/nginx-vhosts_8.bats
Labels: merge-level: minor, type: enhancement

#4347 Update plugins.md
  docs/community/plugins.md
Labels: type: documentation

#4348 Correct app-specific shell handling
  plugins/app-json/functions.go
Labels: type: bug

#4337 Add logrotation to container log files
  docs/deployment/logs.md
  docs/development/plugin-triggers.md
  plugins/common/properties.go
  plugins/logs/.gitignore
  plugins/logs/Makefile
  plugins/logs/logs.go
  plugins/logs/report.go
  plugins/logs/set.go
  plugins/logs/src/subcommands/subcommands.go
  plugins/logs/src/triggers/triggers.go
  plugins/logs/subcommands.go
  plugins/logs/triggers.go
  tests/unit/logs.bats
Labels: merge-level: minor, type: enhancement

#4351 Set hostname for CI runs
  .github/commands/ci-setup
Labels: type: tests

#4349 Remove need for internal dokku calls
  docs/appendices/0.23.0-migration-guide.md
  docs/development/plugin-triggers.md
  docs/getting-started/upgrading.md
  dokku
  plugins/00_dokku-standard/subcommands/report
  plugins/20_events/storage-list
  plugins/common/functions
  plugins/plugin/internal-functions
  plugins/scheduler-docker-local/pre-deploy
  plugins/storage/functions
  plugins/storage/internal-functions
  plugins/storage/storage-list
Labels: type: refactor

#4350 Add missing trigger event
  plugins/20_events/scheduler-register-retired
Labels: type: bug

#4300 allow disabling hsts globally and explicitly enable per app
  docs/configuration/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/subcommands/set
  tests/unit/nginx-vhosts_6.bats
Labels: merge-level: minor, type: enhancement

#4354 Log all triggers called by golang in trace output
  plugins/common/subprocess.go
Labels: type: enhancement

#4336 Add ability to manage stacks on an app or global level …
  docs/configuration/environment-variables.md
  docs/deployment/methods/cloud-native-buildpacks.md
  docs/deployment/methods/herokuish-buildpacks.md
  dokku
  plugins/builder-cnb/builder-build
  plugins/builder-dockerfile/builder-build
  plugins/builder-herokuish/builder-build
  plugins/buildpacks/.gitignore
  plugins/buildpacks/Makefile
  plugins/buildpacks/buildpacks.go
  plugins/buildpacks/report.go
  plugins/buildpacks/src/commands/commands.go
  plugins/buildpacks/src/subcommands/subcommands.go
  plugins/buildpacks/src/triggers/triggers.go
  plugins/buildpacks/subcommands.go
  plugins/buildpacks/triggers.go
  plugins/common/functions
  plugins/logs/logs.go
  plugins/repo/.gitignore
  plugins/repo/Makefile
  plugins/repo/src/triggers/triggers.go
Labels: merge-level: minor, needs: tests, type: enhancement

#4355 Allow underscores in vector schemes
  plugins/logs/.gitignore
  plugins/logs/functions.go
  plugins/logs/set.go
  tests/unit/logs.bats
Labels: type: bug

#4352 Add a test for application renames
  plugins/plugin/subcommands/trigger
  tests/unit/ps-general.bats
Labels: type: tests

#4356 Do not retag images unnecessarily
  Makefile
  debian/control
  docker/etc/sudoers.d/dokku-docker
  docker/usr/local/bin/docker-image-labeler
  docs/appendices/0.23.0-migration-guide.md
  plugins/builder-cnb/builder-release
  plugins/builder-dockerfile/builder-release
  plugins/builder-herokuish/builder-release
  rpm.mk
  tests/ci/setup.sh
  tests/unit/tags.bats
Labels: type: bug

#4357 Fix spelling in nginx documentation
  docs/configuration/nginx.md
Labels: type: documentation

#4358 Update header on cron documentation
  docs/processes/scheduled-cron-tasks.md
Labels: type: documentation

#4359 Fix command call for set-property
  docs/deployment/methods/cloud-native-buildpacks.md
  docs/deployment/methods/herokuish-buildpacks.md
Labels: type: documentation

#4363 Refer to the monitored slack and github discussions channels in the issue template
  ISSUE_TEMPLATE.md
Labels: type: documentation
