Repository dokku/dokku, pull requests merged in 2021-09, with the labels that each got.

#4760 Add missing rsync to OS dependency list for git:sync command
  debian/control
  rpm.mk
Labels: type: bug, plugin: git

#4761 Correct permissions for userns support
  docker/etc/my_init.d/10_dokku_init
Labels: type: enhancement

#4763 Remove install doc references to removed web installer
  README.md
  docs/home.html
Labels: type: documentation

#4764 Reference correct plugin when setting up app-json plugin
  plugins/app-json/triggers.go
Labels: type: bug

#4766 Capitalize certain log messages for aesthetic reasons
  plugins/checks/install
  plugins/nginx-vhosts/functions
Labels: merge-level: patch

#4741 Use a Dockerfile to speed up env var injection for herokuish app builds
  plugins/builder-herokuish/builder-release
  plugins/builder-herokuish/dockerfiles/builder-release.Dockerfile
  plugins/builder-herokuish/dockerfiles/pre-build.Dockerfile
  plugins/builder-herokuish/pre-build-buildpack
Labels: type: refactor, merge-level: patch

#4767 Output logs when container rename fails and continue on
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/core-post-deploy
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: bug, merge-level: patch

#4776 Clarify valid values for container-type when entering containers
  docs/processes/entering-containers.md
Labels: type: documentation

#4777 Set correct version for registry plugin
  plugins/registry/plugin.toml
Labels: type: bug

#4775 Add support for url-encoded vector-sink config values …
  docs/deployment/logs.md
  plugins/common/properties.go
  plugins/logs/functions.go
  tests/unit/logs.bats
Labels: type: bug, merge-level: patch

#4780 Update source for `dokku-update`
  docs/getting-started/upgrading.md
Labels: type: documentation

#4785 Add support for VSCode Dev Containers
  .devcontainer/Dockerfile
  .devcontainer/bin/copy-plugin
  .devcontainer/devcontainer.json
Labels: type: enhancement, merge-level: patch

#4786 Add missing argument from trigger documentation
  docs/development/plugin-triggers.md
Labels: type: documentation

#4796 Remove the --restart flag from pre-deploy chown containers
  plugins/scheduler-docker-local/pre-deploy
Labels: type: bug

#4791 Fix test running in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  tests/unit/test_helper.bash
Labels: type: tests

#4800 Add help2man os package for copyfiles make target to devcontainer
  .devcontainer/Dockerfile
Labels: type: bug, merge-level: patch

#4784 feat: upgrade vector image to 0.16.x
  plugins/logs/logs.go
Labels: type: enhancement, merge-level: patch, type: bc break

#4801 Expose git-from-archive and git-from-image plugin triggers
  docs/development/plugin-triggers.md
  plugins/20_events/git-from-archive
  plugins/20_events/git-from-directory
  plugins/20_events/git-from-image
  plugins/git/git-from-archive
  plugins/git/git-from-image
  plugins/git/internal-functions
Labels: type: enhancement, merge-level: patch, plugin: git

#4807 Docs: Fix instructions for enabling Docker Buildkit
  docs/deployment/builders/dockerfiles.md
Labels: type: documentation

#4808 Added a comment about Dockerfile deployment
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#4812 Silence stderr when fetching a command from the Procfile
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: bug

#4809 Implement storage:ensure-directory command
  docs/advanced-usage/persistent-storage.md
  plugins/storage/bin/chown-storage-dir
  plugins/storage/help-functions
  plugins/storage/install
  plugins/storage/internal-functions
  plugins/storage/subcommands/ensure-directory
  tests/unit/storage.bats
Labels: type: enhancement, merge-level: patch, plugin: storage
