Repository dokku/dokku, pull requests merged in 2021-08, with the labels that each got.

#4508 Add support for the formation key in app.json
  docs/appendices/0.25.0-migration-guide.md
  docs/development/plugin-triggers.md
  docs/processes/process-management.md
  plugins/app-json/appjson.go
  plugins/app-json/functions.go
  plugins/app-json/triggers.go
  plugins/checks/subcommands/run
  plugins/common/common.go
  plugins/common/properties.go
  plugins/common/src/prop/prop.go
  plugins/network/network.go
  plugins/nginx-vhosts/functions
  plugins/ps/.gitignore
  plugins/ps/Makefile
  plugins/ps/functions.go
  plugins/ps/ps.go
  plugins/ps/src/triggers/triggers.go
  plugins/ps/subcommands.go
  plugins/ps/triggers.go
  plugins/scheduler-docker-local/core-post-deploy
  plugins/scheduler-docker-local/scheduler-deploy
  tests/unit/nginx-vhosts_2.bats
  tests/unit/ps-general.bats
Labels: merge-level: minor, needs: tests, type: refactor

#4709 Add migration note for deprecation of ubuntu 16.04
  docs/appendices/0.25.0-migration-guide.md
Labels: type: documentation

#4712 Clarify the shape of the command that should be entered in app.json for a cron task
  docs/processes/scheduled-cron-tasks.md
Labels: type: documentation

#4714 Swap from freenode to libera.chat
  CONTRIBUTING.md
  README.md
  docs/getting-started/where-to-get-help.md
  docs/home.html
  docs/template.html
Labels: type: documentation, merge-level: patch

#4711 Enable installing on RPM systems where bind-utils is bindutils
  rpm.mk
Labels: type: enhancement, merge-level: patch

#4460 Implement registry plugin
  .github/workflows/ci.yml
  docs/advanced-usage/registry-management.md
  docs/appendices/0.25.0-migration-guide.md
  docs/deployment/schedulers/alternate-schedulers.md
  docs/deployment/schedulers/docker-local.md
  docs/development/plugin-triggers.md
  docs/template.html
  docs/viewdocs.json
  plugins/20_events/post-release-builder
  plugins/app-json/triggers.go
  plugins/builder-dockerfile/builder-release
  plugins/builder-herokuish/builder-release
  plugins/builder-pack/builder-release
  plugins/builder/report.go
  plugins/builder/subcommands.go
  plugins/common/docker.go
  plugins/common/functions
  plugins/common/subprocess.go
  plugins/config/docker-args-deploy
  plugins/ps/triggers.go
  plugins/registry/.gitignore
  plugins/registry/Makefile
  plugins/registry/functions.go
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/registry/plugin.toml
  plugins/registry/registry.go
  plugins/registry/report.go
  plugins/registry/src/commands/commands.go
  plugins/registry/src/subcommands/subcommands.go
  plugins/registry/src/triggers/triggers.go
  plugins/registry/subcommands.go
  plugins/registry/triggers.go
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/pre-deploy
  plugins/scheduler-docker-local/scheduler-deploy
  tests/unit/registry.bats
Labels: type: enhancement, merge-level: minor, needs: tests

#4718 Update link to azure installation on homepage
  docs/home.html
Labels: type: documentation, merge-level: patch

#4715 Switch from xip.io to sslip.io
  docs/getting-started/install/azure.md
  plugins/common/functions
  tests/unit/nginx-vhosts_5.bats
Labels: type: enhancement

#4716 Suppress dos2unix stderr output during Dockerfile builds
  plugins/builder-dockerfile/builder-build
Labels: type: bug

#4713 Make heroku-20/focal the default stack for herokuish builds
  Makefile
  docs/appendices/0.25.0-migration-guide.md
  docs/deployment/builders/herokuish-buildpacks.md
  dokku
  tests/apps/dockerfile/app.json
  tests/apps/multi/Gemfile
  tests/apps/nodejs-express/app.json
  tests/apps/ruby/Gemfile
Labels: type: enhancement, merge-level: minor, type: bc break

#4717 Silence stderr when checking for ufw on debian systems
  contrib/dokku-installer.py
Labels: type: bug, merge-level: patch

#4719 Add support for routing an app to a specified host:port
  docs/deployment/builders/null.md
  docs/deployment/schedulers/null.md
  docs/development/plugin-triggers.md
  docs/networking/network.md
  plugins/builder-null/commands
  plugins/builder-null/help-functions
  plugins/builder-null/plugin.toml
  plugins/network/Makefile
  plugins/network/network.go
  plugins/network/report.go
  plugins/network/src/triggers/triggers.go
  plugins/network/triggers.go
  plugins/nginx-vhosts/functions
  plugins/scheduler-null/commands
  plugins/scheduler-null/help-functions
  plugins/scheduler-null/plugin.toml
  plugins/scheduler-null/scheduler-is-deployed
  tests/unit/proxied-app.bats
Labels: type: enhancement, merge-level: minor

#4721 Recursively sync submodules
  plugins/git/internal-functions
Labels: type: bug

#4693 Add package.lock for test app
  tests/apps/multi/package-lock.json
  tests/apps/multi/package.json
Labels: type: tests

#4723 Clarify buildkit instructions
  docs/deployment/builders/dockerfiles.md
Labels: type: documentation

#4726 Drop web installer in favor of setup via cli
  .dockerignore
  Dockerfile
  Makefile
  Vagrantfile
  bootstrap.sh
  contrib/dokku-installer.py
  contrib/release-dokku
  debian/config
  debian/lintian-overrides
  debian/postinst
  debian/preinst
  debian/templates
  docs/appendices/0.25.0-migration-guide.md
  docs/deployment/user-management.md
  docs/development/plugin-triggers.md
  docs/getting-started/advanced-installation.md
  docs/getting-started/install/debian.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/dreamhost.md
  docs/getting-started/install/vagrant.md
  docs/getting-started/installation.md
  package.mk
  plugins/00_dokku-standard/install
  plugins/common/functions
  plugins/domains/functions
  plugins/nginx-vhosts/functions
  tests/ci/setup.sh
  tests/unit/domains.bats
  tests/unit/network.bats
  tests/unit/nginx-vhosts_1.bats
  tests/unit/nginx-vhosts_10.bats
  tests/unit/nginx-vhosts_11.bats
  tests/unit/nginx-vhosts_2.bats
  tests/unit/nginx-vhosts_3.bats
  tests/unit/nginx-vhosts_4.bats
  tests/unit/nginx-vhosts_5.bats
  tests/unit/nginx-vhosts_6.bats
  tests/unit/nginx-vhosts_7.bats
  tests/unit/nginx-vhosts_8.bats
  tests/unit/nginx-vhosts_9.bats
  tests/unit/proxy.bats
  tests/unit/test_helper.bash
Labels: type: refactor, merge-level: minor, type: bc break

#4729 Correct count check for user-auth trigger
  plugins/common/functions
Labels: type: bug

#4730 Execute motd at the end of the install
  bootstrap.sh
Labels: type: enhancement

#4731 Respect debconf selections where possible
  debian/postinst
Labels: type: bug

#4732 Ensure image cleanup does not impact the stack image and refactor container/image cleanup
  docs/appendices/0.25.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/apps/functions.go
  plugins/builder-herokuish/builder-build
  plugins/common/docker.go
  plugins/common/functions
  plugins/common/src/common/common.go
  plugins/ps/src/subcommands/subcommands.go
  plugins/ps/subcommands.go
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/scheduler-docker-cleanup
  plugins/scheduler-docker-local/scheduler-register-retired
  plugins/scheduler-docker-local/scheduler-retire
Labels: type: bug

#4733 Force grep to run in quiet mode in domains:add call
  plugins/domains/functions
Labels: type: bug

#4734 docs: add github sponsorship link to contributing docs
  CONTRIBUTING.md
Labels: type: documentation

#4736 Ensure herokuish deploys respects the env vars during the release process
  plugins/common/functions
  plugins/registry/triggers.go
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/scheduler-deploy
  plugins/scheduler-docker-local/scheduler-run
  tests/apps/python/release.py
  tests/unit/app-json.bats
  tests/unit/builder-pack.bats
  tests/unit/ps-cnb.bats
  tests/unit/run_1.bats
  tests/unit/test_helper.bash
Labels: type: bug, merge-level: patch

#4747 Fix process management references to formation key in app.json
  docs/processes/process-management.md
Labels: type: documentation
