Repository dokku/dokku, pull requests merged in 2021-11, with the labels that each got.

#4899 Ensure we respect quotes and dollar signs in config vars
  plugins/config/docker-args-deploy
  tests/unit/config.bats
Labels: type: bug

#4906 Upgrade ci linters
  .github/workflows/lint.yml
Labels: type: tests

#4910 Fix typo on persistent storage docs
  docs/advanced-usage/persistent-storage.md
Labels: type: documentation

#4911 Add initial dokku-pro documentation
  docs/enterprise/pro.md
  docs/home.html
  docs/template.html
Labels: type: documentation

#4915 Add support for --global flag to network:set command
  plugins/network/src/subcommands/subcommands.go
Labels: type: bug

#4916 Ignore new SC2295 shellcheck warning
  .github/workflows/lint.yml
  tests/shellcheck-exclude
Labels: type: tests

#4917 Update golang to fix golang tests
  common.mk
  plugins/app-json/go.mod
  plugins/apps/go.mod
  plugins/builder/go.mod
  plugins/buildpacks/go.mod
  plugins/common/go.mod
  plugins/config/go.mod
  plugins/cron/go.mod
  plugins/docker-options/go.mod
  plugins/logs/go.mod
  plugins/network/go.mod
  plugins/nginx-vhosts/go.mod
  plugins/proxy/go.mod
  plugins/ps/go.mod
  plugins/registry/go.mod
  plugins/repo/go.mod
  plugins/resource/go.mod
  plugins/scheduler/go.mod
  tests/apps/zombies-buildpack/go.mod
  tests/apps/zombies-dockerfile-no-tini/go.mod
  tests/apps/zombies-dockerfile-tini/go.mod
Labels: type: bug

#4918 Use netrc binary to properly release dokku client homebrew formula
  .github/workflows/release.yml
Labels: type: bug

#4919 fix: do not validate global flag as an app name
  plugins/network/subcommands.go
Labels: type: bug

#4922 Gitignore more built plugin triggers in apps plugin
  plugins/apps/.gitignore
Labels: type: bug

#4920 Ensure related go source and vscode plugins are installed in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/bin/copy-plugin
  .devcontainer/bin/go-mod-downloadall
  .devcontainer/devcontainer.json
  .gitignore
Labels: type: enhancement

#4924 Update devcontainer to include aliased go packages
  .devcontainer/bin/go-mod-downloadall
Labels: type: enhancement

#4935 Reword note about env vars in nginx config templates
  docs/configuration/nginx.md
Labels: type: documentation

#4943 Fix typo in registry management documentation
  docs/advanced-usage/registry-management.md
Labels: type: documentation
