Repository dokku/dokku, pull requests merged in 2021-06, with the labels that each got.

#4632 Fix typo in docs for GitHub Actions
  docs/deployment/continuous-integration/github-actions.md
Labels: type: documentation

#4638 Schedule a retire as early as possible
  plugins/scheduler-docker-local/scheduler-deploy
Labels: merge-level: patch, plugin: schedulers, type: bug

#4635 Add buildkit cache example to Dockerfile docs
  docs/deployment/builders/dockerfiles.md
Labels: type: documentation

#4639 Correct path for azure-vm releases
  .github/commands/bump-azure
Labels: merge-level: patch, type: bug

#4641 Add initial support for installing onto Fedora
  bootstrap.sh
  plugins/20_events/install
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
Labels: type: enhancement

#4644 Update unit test publisher to latest
  .github/workflows/ci.yml
Labels: type: tests

#4507 Drop support for Ubuntu 16.04
  .github/commands/ci-setup
  .github/workflows/ci.yml
  README.md
  bootstrap.sh
  contrib/copy-packages
  contrib/release-dokku
  contrib/release-plugin
  docs/development/testing.md
  docs/getting-started/install/debian.md
  docs/getting-started/installation.md
  docs/home.html
  plugins/git/internal-functions
  plugins/scheduler-docker-local/scheduler-deploy
  tests/unit/core_2.bats
  tests/unit/git_3.bats
Labels: merge-level: minor, type: refactor

#4651 fix: do not attempt to retire when there was no pre-existing container
  plugins/scheduler-docker-local/scheduler-deploy
Labels: merge-level: patch, plugin: schedulers, type: bug

#4661 Fix case style
  README.md
  bootstrap.sh
  docs/community/plugins.md
  docs/deployment/continuous-integration/gitlab-ci.md
  docs/deployment/methods/git.md
  docs/development/release-process.md
  docs/development/testing.md
  docs/getting-started/upgrading.md
  docs/getting-started/where-to-get-help.md
  docs/template.html
  tests/unit/client.bats
Labels: type: documentation
