Repository dokku/dokku, pull requests merged in 2021-04, with the labels that each got.

#4552 Scope return 301 in nginx config to allow proper letsencrypt usage
  plugins/common/property-functions
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  plugins/proxy/functions
Labels: type: bug

#4546 Add bad proxy ports to troubleshooting doc
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#4554 Ensure deployment task containers get associated to internal networks
  plugins/app-json/functions.go
Labels: type: bug

#4484 Bumps vector image version
  plugins/logs/logs.go
Labels: merge-level: minor, type: enhancement

#4557 Add bash-completion to debian package recommends
  debian/control
Labels: merge-level: patch, type: enhancement

#4568 Do not insert log max-size when log-driver is set at daemon-level
  plugins/logs/triggers.go
  tests/unit/logs.bats
Labels: merge-level: patch, type: bug

#4567 Ensure plugin:update updates all plugins when no plugin is specified
  plugins/plugin/subcommands/update
Labels: merge-level: patch, type: bug

#4566 Normalize Dockerfile line terminators to handle issues in port extraction
  plugins/builder-dockerfile/builder-build
  plugins/storage/functions
Labels: merge-level: patch, type: bug

#4563 Tough netrc file when setting git:auth entries
  plugins/git/internal-functions
Labels: merge-level: patch, type: bug

#4493 Ensure alternate-tags is properly injected for git:from-image deploys
  plugins/git/internal-functions
  tests/unit/git_4.bats
Labels: merge-level: patch, type: bug
