Repository dokku/dokku, pull requests merged in 2021-03, with the labels that each got.

#4449 Gitignore trigger symlink
  plugins/builder/.gitignore
  plugins/builder/builder-detect
Labels: type: bug

#4451 Update links to builder documentation to avoid extra rewrite
  HISTORY.md
  docs/appendices/0.5.0-migration-guide.md
  docs/deployment/application-deployment.md
  docs/deployment/builders/cloud-native-buildpacks.md
  docs/deployment/methods/git.md
Labels: type: documentation

#4450 Simplify docker image deploys via git:from-image
  .github/commands/bump-azure
  .github/commands/ci-run
  docs/appendices/0.24.0-migration-guide.md
  docs/deployment/methods/git.md
  docs/deployment/methods/images.md
  docs/development/plugin-triggers.md
  plugins/builder-herokuish/post-app-clone-setup
  plugins/builder-herokuish/post-app-rename-setup
  plugins/git/git-from-directory
  plugins/git/help-functions
  plugins/git/internal-functions
  plugins/git/subcommands/from-image
  tests/unit/git_4.bats
Labels: type: enhancement

#4453 Simplify tar and zip deploys via git:from-archive
  debian/control
  docs/appendices/0.24.0-migration-guide.md
  docs/deployment/methods/git.md
  docs/deployment/methods/tar.md
  plugins/git/git-from-directory
  plugins/git/help-functions
  plugins/git/internal-functions
  plugins/git/subcommands/from-archive
  rpm.mk
  tests/unit/git_5.bats
Labels: type: enhancement

#4454 Use proper title for azure releases and fix tmp dir creation
  .github/commands/bump-azure
Labels: type: bug

#4456 Fix doc link and add 0.24.0 appendix to migration guides
  docs/deployment/methods/git.md
  docs/getting-started/upgrading.md
Labels: type: documentation

#4461 Add dark mode support to documentation site
  docs/assets/style.css
  docs/home.html
  docs/template.html
Labels: type: documentation

#4473 Add the correct log mount for app logs
  plugins/logs/functions.go
Labels: type: bug

#4492 Set better header colors for dark mode
  docs/assets/style.css
Labels: type: documentation

#4496 Ensure existing apps are initialized before modifying with code
  plugins/git/git-from-directory
  tests/unit/git_4.bats
Labels: merge-level: patch, type: bug

#4503 Drop dead newsletter link
  docs/home.html
  docs/template.html
Labels: type: documentation

#4504 Clarify permissions on persistent storage paths
  docs/advanced-usage/persistent-storage.md
Labels: type: documentation

#4506 Add full example for custom nginx log format
  docs/configuration/nginx.md
Labels: type: documentation

#4511 Document removal of nginx site-enabled files for first time installers
  bootstrap.sh
Labels: type: documentation

#4513 Add a note on ssl and letsencrypt usage to the setup docs
  docs/deployment/application-deployment.md
Labels: type: documentation

#4510 Reformat existing buildpacks files
  plugins/buildpacks/functions.go
  plugins/buildpacks/triggers.go
  tests/unit/buildpacks.bats
Labels: merge-level: patch, type: bug

#4516 Properly handle letsencrypt certs in certs:report output
  plugins/certs/internal-functions
Labels: merge-level: patch, type: bug

#4523 Ignore set pipefail errors when DOKKU_SHELL is set to sh
  plugins/app-json/functions.go
Labels: merge-level: patch, needs: tests, type: bug

#4524 Allow skipping entrypoint detection if entrypoint is tini
  docs/advanced-usage/deployment-tasks.md
  plugins/app-json/functions.go
  tests/unit/app-json-2.bats
  tests/unit/app-json.bats
  tests/unit/ps-cnb.bats
Labels: merge-level: patch, type: enhancement

#4530 deployment docs: fix letsencrypt plugin name
  docs/deployment/application-deployment.md
Labels: type: documentation

#4525 Update error for git:from- commands when the artifact is already synced
  docs/development/plugin-triggers.md
  plugins/git/git-from-directory
Labels: merge-level: patch, type: enhancement

#4528 Fix typo in persistent storage docs
  docs/advanced-usage/persistent-storage.md
Labels: merge-level: patch, type: documentation

#4531 Update config command to config:show
  docs/configuration/environment-variables.md
Labels: type: documentation

#4526 Do not cut off builder arguments that have a 'v-' substring
  plugins/builder-dockerfile/builder-build
  tests/unit/docker-options.bats
Labels: merge-level: patch, type: bug
