Repository dokku/dokku, pull requests merged in 2021-07, with the labels that each got.

#4673 Fix comment typo in dokku binary
  dokku
Labels: type: documentation

#4672 Fix typo in pack builder docs
  docs/deployment/builders/cloud-native-buildpacks.md
Labels: type: documentation

#4509 Add ability to specify initial network
  .editorconfig
  docs/appendices/0.25.0-migration-guide.md
  docs/networking/network.md
  plugins/common/.gitignore
  plugins/network/.gitignore
  plugins/network/Makefile
  plugins/network/functions.go
  plugins/network/network.go
  plugins/network/network_test.go
  plugins/network/report.go
  plugins/network/src/triggers/triggers.go
  plugins/network/triggers.go
  tests/unit/network.bats
Labels: merge-level: minor, needs: tests, type: enhancement

#4677 Cleanup markdown lint errors
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  docs/advanced-usage/deployment-tasks.md
  docs/appendices/0.6.0-migration-guide.md
  docs/community/plugins.md
  docs/getting-started/install/digitalocean.md
  docs/networking/dns.md
  docs/processes/scheduled-cron-tasks.md
Labels: type: documentation

#4678 Cleanup markdown lint errors
  docs/advanced-usage/persistent-storage.md
  docs/advanced-usage/resource-management.md
  docs/appendices/0.20.0-migration-guide.md
  docs/community/plugins.md
  docs/configuration/domains.md
  docs/configuration/ssl.md
  docs/deployment/application-deployment.md
  docs/deployment/builders/herokuish-buildpacks.md
  docs/deployment/methods/git.md
  docs/deployment/zero-downtime-deploys.md
  docs/development/plugin-creation.md
  docs/getting-started/advanced-installation.md
  docs/networking/port-management.md
  docs/processes/process-management.md
Labels: type: documentation

#4679 Cleanup markdown lint errors
  docs/advanced-usage/backup-recovery.md
  docs/community/plugins.md
  docs/configuration/environment-variables.md
  docs/configuration/nginx.md
  docs/deployment/application-management.md
  docs/deployment/builders/dockerfiles.md
  docs/deployment/continuous-integration/github-actions.md
  docs/deployment/logs.md
  docs/deployment/user-management.md
  docs/development/plugin-triggers.md
  docs/getting-started/install/rpm.md
  docs/getting-started/troubleshooting.md
  docs/networking/network.md
Labels: type: documentation

#4680 Cleanup markdown lint errors
  docs/deployment/application-management.md
  docs/development/plugin-creation.md
Labels: type: documentation

#4681 Ignore duplication warnings in codacy
  .codacy.yml
Labels: type: tests

#4682 Properly space report output
  plugins/common/common.go
Labels: merge-level: patch, type: enhancement

#4685 tests: Remove ci skip note in PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: type: tests

#4689 Add a note about wildcards in the installation doc page
  docs/getting-started/installation.md
Labels: type: documentation

#4688 Add a note on recovering networks
  docs/advanced-usage/backup-recovery.md
Labels: type: documentation

#4683 Strip published port flags when triggering deploy tasks
  plugins/app-json/functions.go
  plugins/scheduler-docker-local/pre-deploy
Labels: merge-level: patch, type: bug

#4687 Output message explaining how to remove a deploy lock when a lock is encountered
  plugins/common/functions
Labels: merge-level: patch, type: enhancement

#4684 Install gpg-agent in bootstrap script
  bootstrap.sh
Labels: merge-level: patch, type: bug

#4686 Ensure repository is bare when calling git:sync
  plugins/git/internal-functions
Labels: merge-level: patch, type: bug

#4697 Specify that run containers use the same image
  docs/processes/one-off-tasks.md
Labels: type: documentation

#4701 Revamp dokku run command
  docs/appendices/0.25.0-migration-guide.md
  docs/configuration/environment-variables.md
  docs/deployment/remote-commands.md
  docs/processes/one-off-tasks.md
  dokku
  plugins/00_dokku-standard/commands
  plugins/00_dokku-standard/help-functions
  plugins/20_events/scheduler-run-list
  plugins/common/functions
  plugins/cron/functions.go
  plugins/run/commands
  plugins/run/help-functions
  plugins/run/internal-functions
  plugins/run/plugin.toml
  plugins/run/subcommands/default
  plugins/run/subcommands/detached
  plugins/run/subcommands/list
  plugins/scheduler-docker-local/scheduler-run
  plugins/scheduler-docker-local/scheduler-run-list
  tests/unit/app-json-2.bats
  tests/unit/app-json.bats
  tests/unit/core_1.bats
  tests/unit/core_2.bats
  tests/unit/ps-general.bats
  tests/unit/run_1.bats
  tests/unit/run_2.bats
Labels: merge-level: minor, plugin: run, type: bc break, type: refactor
