Repository dokku/dokku, pull requests merged in 2022-08, with the labels that each got.

#5276 Remove duplicate syntax for nginx.conf
  plugins/nginx-vhosts/templates/nginx.conf.sigil
Labels: type: bug, merge-level: patch, plugin: nginx

#5240 Drop support for CentOS, Fedora, OpenSuse, as well as Debian 9
  ISSUE_TEMPLATE.md
  Makefile
  README.md
  Vagrantfile
  bootstrap.sh
  contrib/build-dokku.Dockerfile
  contrib/release-dokku
  docs/appendices/0.28.0-migration-guide.md
  docs/development/plugin-triggers.md
  docs/getting-started/advanced-installation.md
  docs/getting-started/install/rpm.md
  docs/getting-started/installation.md
  docs/getting-started/uninstalling.md
  docs/getting-started/upgrading.md
  plugins/20_events/install
  plugins/common/io.go
  plugins/cron/triggers.go
  plugins/nginx-vhosts/dependencies
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
  plugins/storage/install
  rpm.mk
  rpm/dokku.postinst
Labels: type: refactor, merge-level: minor, type: bc break

#5285 Update all development dependencies
  Makefile
Labels: merge-level: patch

#5227 Drop forwarded port from vagrant setup
  Vagrantfile
Labels: merge-level: minor

#5288 Do not have bottom border float on page
  docs/assets/style.css
Labels: type: documentation

#5202 Add builder-lambda plugin
  Makefile
  debian/control
  docs/deployment/builders/builder-management.md
  docs/deployment/builders/lambda.md
  docs/template.html
  plugins/builder-dockerfile/builder-release
  plugins/builder-lambda/builder-build
  plugins/builder-lambda/builder-detect
  plugins/builder-lambda/builder-release
  plugins/builder-lambda/commands
  plugins/builder-lambda/core-post-extract
  plugins/builder-lambda/dockerfiles/builder-release.Dockerfile
  plugins/builder-lambda/help-functions
  plugins/builder-lambda/install
  plugins/builder-lambda/internal-functions
  plugins/builder-lambda/plugin.toml
  plugins/builder-lambda/post-app-clone-setup
  plugins/builder-lambda/post-app-rename-setup
  plugins/builder-lambda/post-delete
  plugins/builder-lambda/report
  plugins/builder-lambda/subcommands/default
  plugins/builder-lambda/subcommands/report
  plugins/builder-lambda/subcommands/set
  plugins/builder-lambda/templates/samconfig.toml.sigil
  plugins/builder-lambda/templates/template.yaml.sigil
  plugins/common/functions
  tests/apps/lambda-python/function.py
  tests/apps/lambda-python/requirements.txt
  tests/ci/setup.sh
  tests/unit/builder-lambda.bats
Labels: type: enhancement, merge-level: minor, plugin: builders

#5294 Document and enable alternative proxy implementations
  docs/appendices/0.10.0-migration-guide.md
  docs/appendices/0.5.0-migration-guide.md
  docs/configuration/domains.md
  docs/configuration/ssl.md
  docs/development/plugin-triggers.md
  docs/networking/proxies/nginx.md
  docs/networking/proxy-management.md
  docs/processes/process-management.md
  docs/template.html
  docs/viewdocs.json
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/help-functions
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/subcommands/start
  plugins/nginx-vhosts/subcommands/stop
  plugins/proxy/.gitignore
  plugins/proxy/proxy-configure-ports
Labels: merge-level: patch, plugin: nginx, plugin: proxy

#5293 Add an official traefik proxy implementation
  debian/control
  docs/networking/proxies/traefik.md
  docs/template.html
  dokku
  plugins/traefik-vhosts/command-functions
  plugins/traefik-vhosts/commands
  plugins/traefik-vhosts/core-post-deploy
  plugins/traefik-vhosts/docker-args-process-deploy
  plugins/traefik-vhosts/help-functions
  plugins/traefik-vhosts/install
  plugins/traefik-vhosts/internal-functions
  plugins/traefik-vhosts/plugin.toml
  plugins/traefik-vhosts/subcommands/default
  plugins/traefik-vhosts/subcommands/logs
  plugins/traefik-vhosts/subcommands/report
  plugins/traefik-vhosts/subcommands/set
  plugins/traefik-vhosts/subcommands/show-config
  plugins/traefik-vhosts/subcommands/start
  plugins/traefik-vhosts/subcommands/stop
  plugins/traefik-vhosts/templates/compose.yml.sigil
Labels: type: enhancement, merge-level: minor, plugin: proxy

#5296 Fix typo in kubernetes docs
  docs/deployment/schedulers/kubernetes.md
Labels: type: documentation

#5297 Update vector image
  plugins/logs/functions.go
  plugins/logs/logs.go
Labels: type: enhancement, merge-level: minor, plugin: logs, type: bc break

#5298 Set core.bare=true on correct repository path
  plugins/git/internal-functions
Labels: type: bug, merge-level: patch, plugin: git

#5299 Do not trigger restarts when mutating config globally
  plugins/config/config.go
Labels: type: bug, merge-level: patch, plugin: config

#5300 Add the ability to disable the init process
  docs/deployment/schedulers/docker-local.md
  plugins/scheduler-docker-local/bin/scheduler-deploy-process
  plugins/scheduler-docker-local/bin/scheduler-deploy-process-container
  plugins/scheduler-docker-local/internal-functions
  plugins/scheduler-docker-local/subcommands/set
  tests/unit/scheduler-docker-local.bats
Labels: type: enhancement, merge-level: patch, plugin: schedulers

#5313 Fix issues with multiple domains in new proxy plugins
  plugins/caddy-vhosts/docker-args-process-deploy
  plugins/caddy-vhosts/help-functions
  plugins/traefik-vhosts/docker-args-process-deploy
  plugins/traefik-vhosts/help-functions
  plugins/traefik-vhosts/templates/compose.yml.sigil
  tests/unit/caddy.bats
  tests/unit/traefik.bats
Labels: type: bug, merge-level: patch

#5329 Use updated url for gliderlabs slack invite app
  CONTRIBUTING.md
  README.md
  docs/getting-started/where-to-get-help.md
  docs/home.html
  docs/template.html
Labels: type: documentation

#5332 Remove errant semicolon from wget command
  docs/getting-started/installation.md
Labels: type: documentation

#5337 Add note about docker-compose requirement for using the traefik…
  docs/networking/proxies/traefik.md
Labels: type: documentation

#5336 Add note about docker-compose requirement for using the caddy plugin
  docs/networking/proxies/caddy.md
Labels: type: documentation
