Repository dokku/dokku, pull requests merged in 2022-01, with the labels that each got.

#4992 Typo for deploying using image SHA
  docs/deployment/methods/git.md
Labels: type: documentation

#4970 Log the string error and not bytes when there is an issue updating the cron schedule
  plugins/cron/functions.go
Labels: merge-level: patch, plugin: cron

#4964 Add log message when running state is false
  plugins/ps/ps.go
Labels: type: enhancement, merge-level: patch, plugin: ps

#4949 docs: update herokuish upgrade instructions
  docs/getting-started/upgrading.md
Labels: type: documentation, upstream: buildstep/herokuish

#4950 Use exported environment vars during pack build
  plugins/builder-pack/builder-build
  plugins/config/environment.go
  plugins/config/functions.go
  plugins/config/src/subcommands/subcommands.go
  tests/apps/python/bin/pre_compile
  tests/unit/builder-pack.bats
Labels: type: bug

#5003 Respect pre-existing .env files when preparing the herokuish buildenv
  plugins/builder-herokuish/pre-build-buildpack
  tests/apps/python/.env
  tests/apps/python/release.py
  tests/unit/builder-herokuish.bats
Labels: type: bug, merge-level: patch

#5006 Better go mod support in VSCode Dev Containers
  .devcontainer/Dockerfile
  .devcontainer/bin/go-mod-downloadall
  .devcontainer/devcontainer.json
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
  workspace.code-workspace
Labels: type: enhancement

#5009 Clarify installation documentation
  docs/getting-started/advanced-installation.md
  docs/getting-started/install/azure.md
  docs/getting-started/installation.md
Labels: type: documentation

#5010 Add documentation for ps:restore
  docs/processes/process-management.md
Labels: type: documentation

#5014 Clarify that all run containers are removed at the end of process execution
  docs/processes/one-off-tasks.md
Labels: type: documentation

#5015 Avoid popd errors when dokku is run as root
  plugins/builder-dockerfile/core-post-extract
  plugins/builder-pack/core-post-extract
Labels: type: bug

#5016 Properly support the --global flag when detecting the scheduler
  plugins/scheduler/src/triggers/triggers.go
  plugins/scheduler/triggers.go
Labels: type: bug

#4975 add arm64 to the build
  .dockerignore
  Dockerfile
  contrib/build-dokku.Dockerfile
  contrib/release-dokku
  tests/ci/setup.sh
Labels: merge-level: minor

#5018 Add warning for setting PORT environment variable
  docs/networking/port-management.md
Labels: type: documentation

#5017 Add command to clear all proxy configs
  docs/networking/proxy-management.md
  plugins/nginx-vhosts/proxy-clear-config
  plugins/proxy/Makefile
  plugins/proxy/proxy.go
  plugins/proxy/src/commands/commands.go
  plugins/proxy/src/subcommands/subcommands.go
  plugins/proxy/subcommands.go
  plugins/ps/functions.go
  plugins/ps/ps.go
  tests/unit/proxy.bats
Labels: type: enhancement

#5019 Only rename app domains associated with a global domain
  docs/appendices/0.27.0-migration-guide.md
  docs/getting-started/upgrading.md
  plugins/domains/post-app-rename-setup
  tests/unit/domains.bats
Labels: type: bug
