Repository dokku/dokku, pull requests merged in 2022-02, with the labels that each got.

#5035 Fix help flag for logs command
  docs/deployment/logs.md
  plugins/logs/src/commands/commands.go
Labels: type: bug

#5050 Set the default memory unit type to megabytes
  docs/deployment/schedulers/docker-local.md
  plugins/resource/functions.go
  plugins/resource/triggers.go
  tests/unit/resource_1.bats
Labels: type: enhancement, merge-level: patch, plugin: resource

#4921 Add ability to filter returnable apps
  docs/development/plugin-triggers.md
  plugins/20_events/user-auth-app
  plugins/builder-dockerfile/internal-functions
  plugins/builder-pack/internal-functions
  plugins/certs/internal-functions
  plugins/checks/install
  plugins/checks/internal-functions
  plugins/common/Makefile
  plugins/common/common.go
  plugins/common/common_test.go
  plugins/common/functions
  plugins/common/functions.go
  plugins/common/src/triggers/triggers.go
  plugins/common/subprocess.go
  plugins/common/triggers.go
  plugins/docker-options/internal-functions
  plugins/domains/install
  plugins/domains/internal-functions
  plugins/git/install
  plugins/git/internal-functions
  plugins/logs/go.mod
  plugins/nginx-vhosts/command-functions
  plugins/ps/subcommands.go
  plugins/scheduler-docker-local/internal-functions
  plugins/storage/internal-functions
Labels: type: refactor, merge-level: minor

#5051 Ensure vector component sources have valid names
  plugins/logs/functions.go
  tests/unit/logs.bats
Labels: type: bug
