Repository dokku/dokku, pull requests merged in 2022-09, with the labels that each got.

#5342 Ensure doc links work on github as well as on docs site
  docs/deployment/builders/dockerfiles.md
  docs/deployment/logs.md
  docs/deployment/schedulers/docker-local.md
  docs/networking/dns.md
  docs/networking/network.md
Labels: type: documentation

#5344 Generate docs via mkdocs
  .dockerignore
  Makefile
  contrib/build-docs
  contrib/sort-mkdocs-versions
  contrib/write-mkdocs
  docs.mk
  docs/_build/Dockerfile
  docs/_build/app-nginx.conf.sigil
  docs/_build/entrypoint
  docs/_build/requirements.txt
  docs/_overrides/main.html
  docs/advanced-usage/persistent-storage.md
  docs/advanced-usage/resource-management.md
  docs/appendices/0.25.0-migration-guide.md
  docs/assets/extra.css
  docs/deployment/application-deployment.md
  docs/deployment/builders/cloud-native-buildpacks.md
  docs/deployment/builders/herokuish-buildpacks.md
  docs/deployment/logs.md
  docs/deployment/schedulers/scheduler-management.md
  docs/deployment/zero-downtime-deploys.md
  docs/getting-started/installation/index.md
  docs/getting-started/upgrading/index.md
  docs/home.html
  docs/networking/dns.md
  docs/networking/network.md
  docs/template.html
  mkdocs.yml
Labels: type: documentation

#5328 Call out git remote change when renaming an app
  docs/deployment/application-management.md
Labels: type: documentation

#5347 Set correct version on builder-lambda plugin
  plugins/builder-lambda/plugin.toml
Labels: type: bug, merge-level: patch

#5351 Fix formatting on list in deployment tasks
  docs/advanced-usage/deployment-tasks.md
Labels: type: documentation

#5354 Report the correct value for the letsencrypt server
  plugins/caddy-vhosts/command-functions
Labels: type: bug

#5355 Autogenerate documentation in CI
  .github/workflows/docs.yml
  contrib/build-docs
Labels: type: documentation

#5357 Reference blog on main domain
  contrib/write-mkdocs
  docs/home.html
  docs/template.html
Labels: type: documentation

#5365 Use correct indentation for embedded list in remote commands documentation
  docs/deployment/remote-commands.md
Labels: type: documentation
