Repository dokku/dokku, pull requests merged in 2022-05, with the labels that each got.

#5166 Ensure permissions for global VHOST file are set to the dokku user on install
  debian/postinst
  plugins/domains/functions
Labels: type: bug

#5168 Add support for Ubuntu 22.04
  bootstrap.sh
  contrib/copy-packages
  contrib/release-dokku
  docs/getting-started/install/debian.md
  docs/home.html
Labels: type: enhancement

#5176 Update installation requirements to mention arm64 and ubuntu 22.04
  docs/getting-started/installation.md
Labels: type: documentation

#5177 docs: cleanup experimental warning in scheduler docs
  docs/deployment/schedulers/kubernetes.md
  docs/deployment/schedulers/nomad.md
Labels: type: documentation

#5178 Fix app filtering for authenticated usage
  docs/development/plugin-triggers.md
  plugins/20_events/app-list
  plugins/checks/install
  plugins/common/common.go
  plugins/common/functions
  plugins/common/src/triggers/triggers.go
  plugins/common/triggers.go
  plugins/cron/functions.go
  plugins/domains/install
  plugins/git/install
  plugins/logs/functions.go
  plugins/network/triggers.go
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/install
  plugins/ps/triggers.go
  plugins/scheduler/triggers.go
Labels: type: bug

#5179 Fixes to the Docs version switcher
  docs/assets/style.css
  docs/template.html
Labels: type: documentation

#5181 Ensure we default SSH_NAME to NAME when filtering apps
  plugins/common/functions.go
Labels: type: bug

#5193 Force-set correct permissions on env files
  plugins/config/config.go
  plugins/config/environment.go
Labels: type: bug

#5192 Confirm installation of universe packages when installing on ubuntu
  bootstrap.sh
Labels: type: bug

#5194 Upgrade base Dockerfile image to phusion/baseimage:focal-1.2.0
  Dockerfile
Labels: type: enhancement

#5196 Disable herokuish usage on both armhf and arm64 platforms
  plugins/00_dokku-standard/subcommands/report
  plugins/builder-herokuish/builder-detect
Labels: type: enhancement

#5199 Revert "fix: Vector fails to start container due to --watch-config flag"
  plugins/logs/functions.go
Labels: type: bug

#5183 Filter apps when verifying app names
  plugins/common/common.go
  plugins/common/common_test.go
  plugins/common/functions
  plugins/common/log.go
  plugins/common/src/common/common.go
  plugins/config/Makefile
  plugins/config/config_test.go
  plugins/config/environment.go
  plugins/config/functions
  plugins/config/functions.go
  plugins/config/src/config_sub/config_sub.go
  plugins/config/subcommands.go
  plugins/config/triggers.go
Labels: type: bug
