Repository dokku/dokku, pull requests merged in 2023-05, with the labels that each got.

#5850 Only run packer validation if any packer-related files were changed
  .github/workflows/lint.yml
Labels: type: tests

#5853 Always overwrite bootstrap install file
  HISTORY.md
  README.md
  contrib/release-dokku
  docs/getting-started/advanced-installation.md
  docs/getting-started/installation/index.md
  docs/home.html
Labels: type: documentation

#5786 Detect id_ed25519.pub in git:public-key command
  plugins/git/internal-functions
Labels: type: bug, merge-level: patch

#5851 Allow setting _ as domain name for default nginx routing
  plugins/domains/functions
  tests/unit/domains.bats
Labels: type: enhancement, merge-level: patch

#5863 Update application-deployment.md
  docs/deployment/application-deployment.md
Labels: type: documentation

#5862 Stop using the `latest` tag for the default `DOKKU_CNB_BUILDER`
  dokku
Labels: type: enhancement, plugin: builders

#5867 Update linuxserver image used in tests to one that is compatible with arm64
  tests/unit/git_4.bats
  tests/unit/git_7.bats
Labels: type: tests

#5870 Repair malformed code-block
  docs/processes/one-off-tasks.md
Labels: type: documentation

#5873 Add dependabot to all plugin dependencies
  .github/dependabot.yml
Labels: type: enhancement

#5886 chore: bump github.com/otiai10/copy from 1.9.0 to 1.11.0
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: dependencies

#5757 Ensure users can push from an image-deploy repository and respect deploy-branch
  plugins/git/git-from-directory
  plugins/git/internal-functions
  tests/unit/git_4.bats
Labels: type: bug, merge-level: patch, plugin: git

#5890 Add missing report triggers and omitted proxy functionality
  plugins/builder-herokuish/report
  plugins/caddy-vhosts/report
  plugins/haproxy-vhosts/command-functions
  plugins/haproxy-vhosts/pre-restore
  plugins/haproxy-vhosts/report
  plugins/traefik-vhosts/report
Labels: type: bug, plugin: proxy

#5889 Respect dashboard disabling properties in traefik
  plugins/traefik-vhosts/templates/compose.yml.sigil
  tests/unit/traefik.bats
Labels: type: bug, merge-level: patch, plugin: traefik

#5495 Move herokuish app cache from the filesystem into a docker volume
  docs/appendices/0.31.0-migration-guide.md
  docs/getting-started/upgrading/index.md
  plugins/builder-herokuish/builder-build
  plugins/builder-herokuish/install
  plugins/common/docker.go
  plugins/common/subprocess.go
  plugins/repo/.gitignore
  plugins/repo/Makefile
  plugins/repo/repo.go
  plugins/repo/src/triggers/triggers.go
  tests/unit/build-env.bats
  tests/unit/repo.bats
  tests/unit/test_helper.bash
Labels: type: refactor, merge-level: minor, type: bc break

#5897 Add cron-restart to plugin registry
  docs/community/plugins.md
Labels: type: documentation
