Repository dokku/dokku, pull requests merged in 2023-06, with the labels that each got.

#5905 fix: trim whitespace on registry property values
  plugins/registry/functions.go
  plugins/registry/report.go
  plugins/registry/triggers.go
Labels: type: bug

#5921 Update dockerfiles.md to mention that BuildKit is the default builder from Docker v24 onwards
  docs/deployment/builders/dockerfiles.md
Labels: type: documentation

#5926 Update default herokuish version to 0.6.0
  Makefile
  tests/ci/setup.sh
Labels: type: enhancement

#5937 chore: update go packages to fix build issues
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: merge-level: patch, type: dependencies, go

#5930 Fix issue with docker plugin-list install failing boot for docker-based installations
  docker/etc/my_init.d/10_dokku_init
Labels: type: bug

#5938 Add build-base to ensure gcc is available
  docs/_build/Dockerfile
Labels: type: documentation

#5941 Use github token to avoid rate limiting during packer init
  .github/workflows/lint.yml
Labels: type: bug, merge-level: patch

#5943 Add a note for each network type mentioning when they are best used
  docs/networking/network.md
Labels: type: documentation, merge-level: patch, plugin: network

#5944 Add the ability to skip ci when commit message includes a ci skip message or are docs related
  .github/workflows/ci.yml
Labels: merge-level: patch, type: tests

#5946 Update to actions/checkout@v3
  .github/workflows/ci.yml
Labels: type: dependencies

#5957 chore: update go packages to fix build issues
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: merge-level: patch, type: dependencies, go

#5962 Add Debian 12 support to the bootstrap install script
  bootstrap.sh
Labels: type: enhancement
