Repository dokku/dokku, pull requests merged in 2023-04, with the labels that each got.

#5799 Add ability to run dokku report without downloading herokuish image
  plugins/00_dokku-standard/subcommands/report
Labels: type: enhancement

#5810 Fix typo in 0.30.x migration guide
  docs/appendices/0.30.0-migration-guide.md
Labels: type: documentation

#5827 Add permalink support to headers
  mkdocs.yml
Labels: type: documentation

#5828 Add a note to the troubleshooting docs pointing developers to bind to all interfaces
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#5758 Support pack-based images that do not have a Procfile
  plugins/builder-pack/docker-args-process-deploy
  tests/unit/builder-pack.bats
Labels: type: bug, merge-level: patch, plugin: builders
