Repository dokku/dokku, pull requests merged in 2023-09, with the labels that each got.

#6177 Update shellcheck junit integration for newer version of shellcheck
  tests/shellcheck-to-junit
Labels: type: tests

#6191 chore: remove debug logging from git plugin
  plugins/git/functions
Labels: merge-level: patch, plugin: git

#6207 docs(Dockerfiles): fix wrong command
  docs/deployment/builders/dockerfiles.md
Labels: type: documentation

#6222 Install docker-buildx-plugin to silence buildx warnings
  debian/control
Labels: type: enhancement

#6224 Correct typo in example app.json for healthchecks
  docs/deployment/zero-downtime-deploys.md
Labels: type: documentation

#6228 Update all go modules and ensure all are tracked in dependabot
  .github/dependabot.yml
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: merge-level: patch, type: dependencies
