Repository dokku/dokku, pull requests merged in 2023-08, with the labels that each got.

#6081 Use correct namespace for haproxy service state tracking
  plugins/haproxy-vhosts/command-functions
Labels: type: bug, plugin: haproxy

#6094 Correct assertion for dockerfile builds when a variable is eval'd
  tests/unit/builder-dockerfile.bats
Labels: type: tests, plugin: builders

#6095 Remove assertion for unconsumed build arguments
  tests/unit/docker-options.bats
Labels: type: tests, plugin: docker-options

#6096 Upgrade vector image from 0.23.x to 0.31.x
  plugins/logs/logs.go
Labels: type: enhancement, plugin: logs, type: bc break

#6097 Upgrade caddy image from 2.7 to 2.8
  plugins/caddy-vhosts/internal-functions
Labels: type: enhancement, plugin: caddy

#6098 Upgrade traefik image from v2.8 to v2.10
  plugins/traefik-vhosts/internal-functions
Labels: type: enhancement, plugin: traefik

#6099 Clean up references in proxy plugins
  docs/networking/proxies/caddy.md
  docs/networking/proxies/haproxy.md
  docs/networking/proxies/traefik.md
  plugins/caddy-vhosts/command-functions
  plugins/haproxy-vhosts/command-functions
  plugins/traefik-vhosts/command-functions
Labels: type: documentation, plugin: caddy, plugin: traefik, plugin: haproxy

#6100 Add support for non-web healthchecks via app.json
  Makefile
  contrib/images/digitalocean/in_parts/012-dokku-packages
  debian/control
  docker/etc/sudoers.d/dokku-docker
  docker/usr/local/bin/docker-container-healthchecker
  docs/appendices/0.31.0-migration-guide.md
  docs/deployment/zero-downtime-deploys.md
  docs/development/plugin-triggers.md
  docs/processes/process-management.md
  plugins/20_events/app-json-get-content
  plugins/app-json/Makefile
  plugins/app-json/src/triggers/triggers.go
  plugins/app-json/triggers.go
  plugins/scheduler-docker-local/check-deploy
  tests/ci/setup.sh
  tests/unit/checks.bats
Labels: type: enhancement, merge-level: minor

#6102 Deprecate ARM as a build target
  docs/appendices/0.31.0-migration-guide.md
Labels: type: bc break

#6103 feat: timeout docker image builds in CI
  .github/workflows/ci.yml
Labels: type: tests

#6110 Correctly handle rebase when generating release notes for minor/major releases
  contrib/release-dokku
Labels: type: bug

#6116 Remove extra newline in migration docs
  docs/appendices/0.31.0-migration-guide.md
Labels: type: documentation

#6123 Add a migration guide for 0.32.x
  docs/appendices/0.32.0-migration-guide.md
  docs/getting-started/upgrading/index.md
Labels: type: documentation

#6124 Add a shell function to check if a plugin trigger exists
  plugins/common/functions
  plugins/common/src/common/common.go
Labels: type: enhancement

#6125 Deprecate the builder-specific pre-build-* triggers in favor of a global pre-build trigger
  docs/appendices/0.32.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/builder-dockerfile/builder-build
  plugins/builder-herokuish/builder-build
  plugins/builder-lambda/builder-build
  plugins/builder-pack/builder-build
Labels: type: deprecation

#6126 Deprecate the builder-specific post-build-* triggers in favor of a global post-build trigger
  docs/appendices/0.32.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/builder-dockerfile/builder-build
  plugins/builder-herokuish/builder-build
  plugins/builder-lambda/builder-build
  plugins/builder-pack/builder-build
Labels: type: deprecation

#6121 Add missing error-log-path function to openresty plugin
  plugins/openresty-vhosts/docker-args-process-deploy
  plugins/openresty-vhosts/internal-functions
Labels: type: bug, plugin: openresty

#6130 Correct package for container healthchecker when building digitalocean image
  contrib/images/digitalocean/in_parts/012-dokku-packages
Labels: type: bug, merge-level: patch

#6131 Ensure tmp files are cleaned up when commands exit
  docs/development/plugin-creation.md
  plugins/scheduler-docker-local/bin/scheduler-deploy-process
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/scheduler-deploy
Labels: type: bug, merge-level: patch

#6132 Add the ability to specify a custom mailto for all cron output
  docs/development/plugin-triggers.md
  docs/processes/scheduled-cron-tasks.md
  plugins/20_events/cron-get-property
  plugins/cron/Makefile
  plugins/cron/cron.go
  plugins/cron/report.go
  plugins/cron/set.go
  plugins/cron/src/triggers/triggers.go
  plugins/cron/subcommands.go
  plugins/cron/templates/cron.tmpl
  plugins/cron/triggers.go
  plugins/scheduler-docker-local/functions.go
Labels: type: enhancement, merge-level: minor, needs: tests, plugin: cron

#6133 Properly handle tag and branch pushes
  plugins/git/functions
  tests/unit/git_8.bats
Labels: type: bug, merge-level: patch, plugin: git

#6149 Fix issue where CI cannot install docker-compose-plugin
  .github/workflows/ci.yml
  tests.mk
Labels: type: tests

#6150 Correct issue where temp file cleanup fails deploy
  plugins/scheduler-docker-local/check-deploy
Labels: type: bug, merge-level: patch, plugin: schedulers

#6151 Do not pass an empty argument to scheduler-run when triggering cron tasks manually
  plugins/cron/subcommands.go
Labels: type: bug, merge-level: patch, plugin: cron

#6152 Use buildjet for building arm images
  .github/actions/build-image/action.yml
  .github/workflows/ci.yml
Labels: merge-level: patch, type: tests

#6153 Fix superscript typos in plugin documentation
  docs/community/plugins.md
Labels: type: documentation

#6155 Remove ARM support
  .github/actions/build-image/action.yml
  .github/workflows/ci.yml
  contrib/build-dokku.Dockerfile
  contrib/release-dokku
  docs/appendices/0.32.0-migration-guide.md
  docs/deployment/builders/herokuish-buildpacks.md
  docs/getting-started/installation/index.md
  plugins/00_dokku-standard/subcommands/report
  plugins/builder-herokuish/builder-detect
  plugins/builder-lambda/builder-detect
  plugins/git/functions
  tests/unit/builder-herokuish.bats
Labels: merge-level: minor, type: bc-break, type: removal

#6157 Upgrade lambda-builder dependency
  Makefile
  debian/control
  tests/unit/builder-lambda.bats
Labels: merge-level: patch, type: dependencies

#6158 Upgrade netrc dependency
  Makefile
  debian/control
Labels: merge-level: patch, type: dependencies

#6159 Upgrade procfile-util dependency
  Makefile
  debian/control
Labels: merge-level: patch, type: dependencies

#6160 Upgrade sshcommand dependency
  Makefile
  debian/control
Labels: merge-level: patch, type: dependencies

#6162 Upgrade herokuish to 0.7.1
  Makefile
  debian/control
Labels: merge-level: patch, type: dependencies

#6161 Upgrade sigil to 0.10.1
  Makefile
  debian/control
Labels: merge-level: patch, type: dependencies

#6163 Add missing triggers for openresty-vhosts plugin
  plugins/openresty-vhosts/post-app-clone-setup
  plugins/openresty-vhosts/post-app-rename-setup
  plugins/openresty-vhosts/post-delete
Labels: type: bug, plugin: openresty

#6166 Remove unused source from openresty trigger
  plugins/openresty-vhosts/post-delete
Labels: type: bug, merge-level: patch, plugin: openresty

#6167 Correct svg path on homepage
  docs/home.html
Labels: type: documentation, merge-level: patch

#6165 Ensure we cleanup extracted files prior to next deployment
  plugins/nginx-vhosts/core-post-extract
  plugins/openresty-vhosts/core-post-extract
  plugins/scheduler-docker-local/core-post-extract
Labels: type: bug, merge-level: patch, plugin: nginx, plugin: schedulers, plugin: openresty

#6164 Use correct path for openresty letsencrypt data
  plugins/openresty-vhosts/install
  plugins/openresty-vhosts/internal-functions
Labels: type: bug, merge-level: patch, plugin: openresty

#6154 Ensure app clones have domains setup
  plugins/domains/functions
  plugins/domains/post-app-clone-setup
  tests/unit/apps_2.bats
  tests/unit/nginx-vhosts_5.bats
  tests/unit/nginx-vhosts_7.bats
  tests/unit/openresty.bats
  tests/unit/test_helper.bash
Labels: type: bug, merge-level: patch, plugin: domains
