Repository dokku/dokku, pull requests merged in 2023-02, with the labels that each got.

#5616 Add a note about reloading nginx to troubleshooting docs
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#5629 Update list indentation explaining network property utilization
  docs/networking/network.md
Labels: needs: documentation

#5630 Remove extra location block from built docs nginx config
  docs/_build/app-nginx.conf.sigil
Labels: type: documentation

#5633 Add auto-updates to docs python dependencies
  .github/dependabot.yml
Labels: type: enhancement

#5632 Add a note mentioning that network aliases only work when attached to a network other than bridge
  docs/networking/network.md
Labels: type: documentation

#5656 Add "new as of" prefix to version in user management docs
  docs/deployment/user-management.md
Labels: type: documentation

#5657 Use correct version of Markdown for mkdocs
  docs/_build/requirements.txt
Labels: type: documentation

#5658 Updated debian install docs to work on both debian and ubuntu
  docs/getting-started/install/debian.md
Labels: type: documentation

#5659 Remove deprecated functions and commands
  docs/appendices/0.30.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/apps/functions
  plugins/common/functions
  plugins/git/functions
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/subcommands/build-config
  plugins/proxy/functions
  tests/unit/nginx-vhosts_1.bats
  tests/unit/nginx-vhosts_10.bats
  tests/unit/nginx-vhosts_11.bats
  tests/unit/nginx-vhosts_2.bats
  tests/unit/nginx-vhosts_4.bats
  tests/unit/nginx-vhosts_5.bats
  tests/unit/nginx-vhosts_6.bats
  tests/unit/nginx-vhosts_7.bats
  tests/unit/nginx-vhosts_8.bats
  tests/unit/nginx-vhosts_9.bats
Labels: type: refactor

#5663 Update build-base docker image to ensure we can build on all supported platforms without stalling
  contrib/build-base.Dockerfile
  contrib/build-dokku.Dockerfile
Labels: type: enhancement

#5559 Move app.json extraction from built image artifact to source code
  docs/appendices/0.30.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/app-json/.gitignore
  plugins/app-json/Makefile
  plugins/app-json/appjson.go
  plugins/app-json/functions.go
  plugins/app-json/go.mod
  plugins/app-json/src/triggers/triggers.go
  plugins/app-json/triggers.go
  plugins/builder/Makefile
  plugins/builder/src/triggers/triggers.go
  plugins/builder/triggers.go
  plugins/common/data.go
  plugins/logs/triggers.go
  plugins/ps/functions.go
  plugins/ps/triggers.go
  tests/apps/python/app3.json
  tests/unit/app-json.bats
Labels: type: refactor, merge-level: minor, plugin: app-json, type: bc break

#5673 Cancel in progress builds when a new commit is pushed
  .github/workflows/ci.yml
Labels: type: tests

#5674 Use authenticated requests to the github api in order to generate changelogs for a release
  .github/workflows/release.yml
  contrib/release-dokku
Labels: type: bug

#5675 Add new sections to release notes
  .github/dependabot.yml
  contrib/release-dokku
Labels: type: enhancement

#5678 Cleanup docs on homepage for installation
  docs/home.html
Labels: type: documentation

#5679 Revert invalid replacement in homepage html path objects
  docs/home.html
Labels: type: documentation

#5682 Build Digitalocean image automatically upon release
  .github/workflows/lint.yml
  .github/workflows/release.yml
  contrib/images/digitalocean/files/etc/nginx/sites-available/digitalocean
  contrib/images/digitalocean/files/etc/update-motd.d/99-one-click
  contrib/images/digitalocean/files/var/lib/cloud/scripts/per-once/001_setup
  contrib/images/digitalocean/files/var/lib/cloud/scripts/per-once/002_enable_ssh
  contrib/images/digitalocean/files/var/www/html/index.html
  contrib/images/digitalocean/in_parts/011-docker
  contrib/images/digitalocean/in_parts/011-ssh-message
  contrib/images/digitalocean/in_parts/012-dokku-packages
  contrib/images/digitalocean/in_parts/012-grub-opts
  contrib/images/digitalocean/in_parts/014-docker-dns
  contrib/images/digitalocean/in_parts/014-ufw-rules
  contrib/images/digitalocean/in_parts/099-application_tag
  contrib/images/digitalocean/in_parts/099-cleanup
  contrib/images/digitalocean/in_parts/100-image-check
  contrib/images/digitalocean/packer.pkr.hcl
  contrib/packer.json
  package.mk
Labels: type: enhancement

#5684 Note that the app.json is pulled from the specified image when deploying via git:from-image
  docs/deployment/methods/git.md
Labels: type: documentation

#5688 Set custom entrypoint for pack-based containers so custom command/argument combinations are respected
  plugins/builder-pack/docker-args-process-deploy
  plugins/builder-pack/docker-args-process-run
Labels: type: bug, merge-level: patch, plugin: builders

#5683 Ensure the services directory also exists
  docker/etc/my_init.d/10_dokku_init
Labels: type: bug, docker

#5689 Add note about ubuntu 18.04 being deprecated
  docs/appendices/0.30.0-migration-guide.md
Labels: type: documentation

#5695 Add a note about required upgrade to 0.29.x for versions prior to 0.25.x
  docs/appendices/0.30.0-migration-guide.md
Labels: type: documentation

#5690 Update dependencies for golang code to fix builds
  .devcontainer/Dockerfile
  common.mk
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: bug
