Repository dokku/dokku, pull requests merged in 2023-10, with the labels that each got.

#6254 Add ci concurrency to codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: type: enhancement

#6253 feat: add ci concurrency to doc building
  .github/workflows/docs.yml
Labels: type: enhancement

#6255 Add ci concurrency to linting workflow
  .github/workflows/lint.yml
Labels: type: enhancement

#6256 chore: bump github.com/otiai10/copy and golang.org/x/sync
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: dependencies

#6271 Update list of official, community, and deprecated plugins
  docs/community/plugins.md
Labels: type: documentation

#6257 Manage Dokku system dependencies in a single file
  .dockerignore
  Makefile
  contrib/build-base.Dockerfile
  contrib/build-dokku.Dockerfile
  contrib/dependencies.json
  contrib/update-deb-dependencies
  deb.mk
  debian/control
  tests/ci/setup.sh
Labels: type: refactor

#6273 Clean up local build images immediately after an image is released
  plugins/builder/functions.go
  plugins/builder/src/triggers/triggers.go
  plugins/builder/triggers.go
  plugins/common/docker.go
Labels: type: bug, merge-level: patch, plugin: builders

#6274 Add more version output to dokku report command
  plugins/00_dokku-standard/subcommands/report
Labels: type: enhancement

#6278 Remove pack installation from builder-lambda tests
  tests/unit/builder-lambda.bats
Labels: type: tests

#6280 Remove more references to ubuntu bionic
  bootstrap.sh
  contrib/images/digitalocean/in_parts/012-dokku-packages
  contrib/release-dokku
Labels: type: bug

#6284 Document future removal of deprecated CHECKS file format
  docs/appendices/0.32.0-migration-guide.md
Labels: type: documentation

#6281 Upgrade golang to 1.21
  .devcontainer/Dockerfile
  common.mk
  contrib/build-dokku.Dockerfile
  docs/development/plugin-triggers.md
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/common/go.mod
  plugins/common/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/nginx-vhosts/go.mod
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
  tests/apps/gogrpc/go.mod
  tests/apps/zombies-buildpack/go.mod
  tests/apps/zombies-dockerfile-no-tini/go.mod
  tests/apps/zombies-dockerfile-tini/go.mod
Labels: merge-level: minor, type: dependencies

#6283 Remove deprecated proxy-ports functions and and plugin subcommands
  docs/appendices/0.32.0-migration-guide.md
  docs/development/plugin-triggers.md
  plugins/20_events/proxy-configure-ports
  plugins/common/functions
  plugins/ports/proxy-configure-ports
  plugins/proxy/go.mod
  plugins/proxy/src/subcommands/subcommands.go
Labels: type: removal

#6287 Recursively delete old custom openresty includes
  plugins/openresty-vhosts/core-post-extract
Labels: type: bug, plugin: openresty

#6286 Remove trailing slash on openresty letsencrypt email
  plugins/openresty-vhosts/templates/compose.yml.sigil
Labels: type: bug, plugin: openresty

#6303 feat: add the ability to specify location-block includes
  plugins/openresty-vhosts/core-post-deploy
  plugins/openresty-vhosts/core-post-extract
  plugins/openresty-vhosts/docker-args-process-deploy
  plugins/openresty-vhosts/internal-functions
  tests/unit/openresty.bats
Labels: type: enhancement, merge-level: patch, plugin: openresty

#6316 Fix docs app-exists plugin trigger description
  docs/development/plugin-triggers.md
Labels: type: documentation
