Repository dokku/dokku, pull requests merged in 2024-04, with the labels that each got.

#6785 Update herokuish requirement to better support readonly containers
  contrib/dependencies.json
Labels: type: enhancement

#6789 Fix typos in documentation
  docs/development/plugin-creation.md
  docs/development/plugin-triggers.md
  docs/getting-started/install/docker.md
  docs/networking/proxies/nginx.md
  docs/processes/entering-containers.md
Labels: type: documentation

#6788 Fix typos in nginx documentation
  docs/networking/proxies/nginx.md
Labels: type: documentation

#6798 Implement missing scheduler-app-status trigger in k3s scheduler plugin
  plugins/scheduler-k3s/Makefile
  plugins/scheduler-k3s/src/triggers/triggers.go
  plugins/scheduler-k3s/triggers.go
Labels: type: bug, merge-level: patch, plugin: scheduler-k3s

#6800 Update message for deployment tasks that execute in ephemeral containers
  plugins/app-json/functions.go
Labels: type: enhancement, plugin: app-json

#6802 Update test for new deployment task output
  tests/unit/app-json.bats
Labels: type: tests, plugin: app-json

#6801 Guard against invalid proxy values due to move of port mapping to ports plugin
  plugins/proxy/subcommands.go
  tests/unit/proxy.bats
Labels: type: bug, plugin: proxy

#6807 chore: bump go modules
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/nginx-vhosts/go.mod
  plugins/nginx-vhosts/go.sum
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler-k3s/go.mod
  plugins/scheduler-k3s/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: dependencies

#6809 Update CI badge in readme
  README.md
Labels: type: documentation

#6823 Remove errant tab character in cron:set help text
  plugins/cron/src/commands/commands.go
Labels: type: documentation

#6821 Add tailscale plugin to community plugin list
  docs/community/plugins.md
Labels: type: documentation

#6835 Add missing local RE_IPV4 & RE_IPV6 vars in core-post-deploy
  plugins/domains/core-post-deploy
Labels: type: bug, plugin: nginx

#6845 chore: update dependencies
  plugins/app-json/go.sum
  plugins/apps/go.sum
  plugins/builder/go.sum
  plugins/buildpacks/go.sum
  plugins/cron/go.sum
  plugins/docker-options/go.sum
  plugins/logs/go.sum
  plugins/network/go.sum
  plugins/nginx-vhosts/go.sum
  plugins/ports/go.sum
  plugins/proxy/go.sum
  plugins/ps/go.sum
  plugins/registry/go.sum
  plugins/repo/go.sum
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler-k3s/go.sum
  plugins/scheduler/go.sum
Labels: type: dependencies

#6808 Traefik optional custom http https entrypoints
  docs/networking/proxies/traefik.md
  plugins/traefik-vhosts/command-functions
  plugins/traefik-vhosts/docker-args-process-deploy
  plugins/traefik-vhosts/internal-functions
  plugins/traefik-vhosts/subcommands/set
  tests/unit/traefik.bats
Labels: plugin: traefik

#6857 Update link to dokku development blog
  docs/development/plugin-creation.md
Labels: type: documentation
