Repository dokku/dokku, pull requests merged in 2024-08, with the labels that each got.

#6983 Clarify paths used by Dokku when looking for specific files
  docs/advanced-usage/deployment-tasks.md
  docs/deployment/builders/cloud-native-buildpacks.md
  docs/deployment/builders/dockerfiles.md
  docs/deployment/builders/lambda.md
  docs/deployment/builders/nixpacks.md
  docs/networking/proxies/nginx.md
  docs/processes/process-management.md
Labels: type: documentation

#7057 Update golang dependencies
  common.mk
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/nginx-vhosts/go.mod
  plugins/nginx-vhosts/go.sum
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler-k3s/go.mod
  plugins/scheduler-k3s/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: dependencies

#7062 List dokku-image-size-limit plugin
  docs/community/plugins.md
Labels: type: documentation

#7071 Bump go version to 1.23.0
  common.mk
  go.work
  plugins/app-json/go.mod
  plugins/apps/go.mod
  plugins/builder/go.mod
  plugins/buildpacks/go.mod
  plugins/common/go.mod
  plugins/config/go.mod
  plugins/cron/go.mod
  plugins/docker-options/go.mod
  plugins/logs/go.mod
  plugins/network/go.mod
  plugins/nginx-vhosts/go.mod
  plugins/ports/go.mod
  plugins/proxy/go.mod
  plugins/ps/go.mod
  plugins/registry/go.mod
  plugins/repo/go.mod
  plugins/resource/go.mod
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-k3s/go.mod
  plugins/scheduler/go.mod
  tests/apps/gogrpc/go.mod
  tests/apps/zombies-buildpack/go.mod
  tests/apps/zombies-dockerfile-no-tini/go.mod
  tests/apps/zombies-dockerfile-tini/go.mod
Labels: type: enhancement, merge-level: minor

#7073 Drop codacy
  .codacy.yml
Labels: merge-level: minor, type: tests

#6784 Remove --restart docker arguments when not running deploy-phase containers
  plugins/docker-options/docker-args-deploy
Labels: type: enhancement, merge-level: minor, needs: tests, plugin: docker-options, type: bc-break

#6762 Upgrade docker compose version in use
  debian/control
  plugins/caddy-vhosts/templates/compose.yml.sigil
  plugins/haproxy-vhosts/templates/compose.yml.sigil
  plugins/logs/templates/compose.yml.tmpl
  plugins/openresty-vhosts/templates/compose.yml.sigil
  plugins/traefik-vhosts/templates/compose.yml.sigil
Labels: type: enhancement, merge-level: minor
