Repository dokku/dokku, pull requests merged in 2024-09, with the labels that each got.

#7077 Add cron dependency because it's necessary to run scheduled cron jobs
  debian/control
Labels: type: bug, merge-level: minor

#7075 Upgrade herokuish builder to gliderlabs/herokuish:latest-24
  Makefile
  docs/appendices/0.31.0-migration-guide.md
  docs/deployment/builders/herokuish-buildpacks.md
  dokku
  tests/apps/dockerfile/app.json
  tests/apps/nodejs-express/app.json
Labels: type: enhancement, merge-level: minor

#7164 fix: remove systemd on docker-based installations
  Dockerfile
Labels: type: bug, merge-level: minor

#7166 Upgrade herokuish from 0.9.2 to 0.10.1
  contrib/dependencies.json
Labels: type: enhancement

#7157 Fix building in vagrant when jq is not available
  Makefile
Labels: type: bug

#7165 Upgrade to Ubuntu Noble 24.04
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  contrib/build-docs
  contrib/release-dokku
  debian/control
  docker/etc/my_init.d/10_dokku_init
  docker/etc/ssh/sshd_config
  docs/_build/entrypoint
  docs/networking/port-management.md
  plugins/20_events/install
  plugins/docker-options/docker-args-deploy
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
  tests/apps/checks-root/.node-version
  tests/apps/checks-root/index.js
  tests/apps/checks-root/package-lock.json
  tests/apps/checks-root/package.json
  tests/apps/dockerfile-release/Procfile
  tests/unit/cron.bats
  tests/unit/ps-general-1.bats
  tests/unit/run_1.bats
Labels: type: enhancement, type: bc-break

#7168 Run CI linting on Ubuntu Noble
  .github/workflows/lint.yml
Labels: type: tests

#7169 Run CI doc generation on Ubuntu Noble
  .github/workflows/docs.yml
Labels: type: tests

#7170 Run CI codeql analysis on Ubuntu Noble
  .github/workflows/codeql-analysis.yml
Labels: type: tests

#7172 Run CI release processes on Ubuntu Noble
  .github/workflows/release.yml
Labels: type: tests

#7147 Support older docker versions by setting ARG value with an equal sign
  plugins/builder-herokuish/dockerfiles/builder-pre-release.Dockerfile
  plugins/builder-herokuish/dockerfiles/builder-release.Dockerfile
  plugins/builder-herokuish/dockerfiles/copy-source.Dockerfile
  plugins/builder-herokuish/dockerfiles/pre-build.Dockerfile
Labels: type: bug

#7101 Fix typo in CNB documentation
  docs/deployment/builders/cloud-native-buildpacks.md
Labels: type: documentation

#7088 Handle the case where parent PID is 0
  debian/prerm
Labels: type: bug

#7174 Upgrade vagrant image to Ubuntu Noble
  Vagrantfile
Labels: type: enhancement

#7175 Upgrade digitalocean image to Ubuntu Noble
  contrib/images/digitalocean/in_parts/012-dokku-packages
  contrib/images/digitalocean/in_parts/100-image-check
  contrib/images/digitalocean/packer.pkr.hcl
Labels: type: enhancement

#7178 Fix link to docs site
  docs/getting-started/where-to-get-help.md
Labels: type: documentation

#7177 Reference noble apt repository and not focal
  Dockerfile
Labels: type: bug

#7176 Fetch packages installed in ci from Ubuntu Noble repo
  tests/ci/setup.sh
Labels: type: tests

#7173 Upgrade builder docker image to Ubuntu Noble
  contrib/build-base.Dockerfile
  contrib/build-dokku.Dockerfile
  deb.mk
Labels: type: enhancement

#7074 Upgrade cnb builder to heroku/builder:24
  docs/deployment/builders/cloud-native-buildpacks.md
  dokku
  tests/apps/python/app-cnb.json
  tests/apps/python/project2.toml
  tests/apps/python/release.py
  tests/unit/builder-pack.bats
Labels: type: enhancement, merge-level: minor

#7180 Reference actual properties for enabling the traefik api and dashboard
  docs/networking/proxies/traefik.md
Labels: type: documentation

#7179 Remove references to version in compose files
  docs/getting-started/install/docker.md
  plugins/caddy-vhosts/templates/compose.yml.sigil
  plugins/haproxy-vhosts/templates/compose.yml.sigil
  plugins/logs/templates/compose.yml.tmpl
  plugins/openresty-vhosts/templates/compose.yml.sigil
  plugins/traefik-vhosts/templates/compose.yml.sigil
Labels: type: bug

#7183 Error out when the Dockerfile is missing during builder-dockerfile execution
  plugins/builder-dockerfile/builder-build
Labels: type: enhancement

#7184 Clear out docker builder cache once a day
  docker/etc/cron.d/docker-builder-prune
  plugins/builder/install-builder-prune
  plugins/builder/triggers.go
Labels: type: enhancement

#7185 Fix vagrant running on arm64 machines
  Vagrantfile
Labels: type: enhancement

#7171 Run CI on Ubuntu Noble
  .github/commands/ci-setup
  .github/workflows/ci.yml
  tests.mk
  tests/ci/setup.sh
Labels: type: tests

#7187 Remove reference to old web ui
  docs/getting-started/install/digitalocean.md
Labels: type: documentation

#7188 Respect GO environment variables when building to ensure CGO is disabled
  Makefile
  go.work
  plugins/app-json/Makefile
  plugins/scheduler-k3s/go.mod
Labels: type: bug

#7190 Allow setting most nginx properties globally
  plugins/nginx-vhosts/subcommands/set
Labels: type: enhancement

#7191 Revert to building Dokku on Ubunut 20.04 Focal to hotfix glibc issues
  contrib/build-dokku.Dockerfile
Labels: type: bug

#7197 Implement missing network:info command
  docs/networking/network.md
  plugins/network/functions.go
  plugins/network/src/commands/commands.go
  plugins/network/src/subcommands/subcommands.go
  plugins/network/subcommands.go
Labels: type: bug

#7198 Add builder-herokuish to default help output
  plugins/builder-herokuish/commands
Labels: type: bug

#7199 Check if nginx is running before reloading during an app deletion
  plugins/nginx-vhosts/install
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/post-delete
Labels: type: bug

#7200 Automatically select a container type if none is specified
  docs/processes/entering-containers.md
  plugins/scheduler-docker-local/scheduler-enter
Labels: type: bug

#7201 Run arm build on 22.04
  .github/workflows/ci.yml
Labels: type: tests

#7208 Compute path for docker-container-healthchecker
  plugins/scheduler-docker-local/check-deploy
  plugins/scheduler-docker-local/install
Labels: type: bug, plugin: scheduler-docker-local

#7210 Ensure pack binary is installed correctly when running tests in a devcontainer
  .devcontainer/Dockerfile
  tests/unit/test_helper.bash
Labels: type: tests

#7211 Always set the git rev env var when building an app via git:sync
  plugins/git/internal-functions
  tests/unit/git_3.bats
Labels: type: bug, plugin: git

#7209 Exit non-zero if any deployment tasks fails
  plugins/common/docker.go
  tests/unit/app-json-4.bats
  tests/unit/app-json.bats
  tests/unit/ps-cnb.bats
  tests/unit/run_1.bats
  tests/unit/test_helper.bash
Labels: type: bug, plugin: app-json

#7213 Release Dokku on supported versions of Debian and Raspbian
  README.md
  bootstrap.sh
  contrib/release-dokku
  docs/getting-started/installation/index.md
Labels: type: enhancement

#7212 Update python version used in test apps
  tests/apps/dockerfile-release/Dockerfile
  tests/apps/python/alt.Dockerfile
  tests/apps/python/dockerfile.Dockerfile
  tests/apps/python/expose.Dockerfile
Labels: type: tests

#7215 Clarify x64 as amd64/arch64 in readme
  README.md
Labels: type: documentation

#7218 Fix reference to arm64
  README.md
Labels: type: documentation
