Repository dokku/dokku, pull requests merged in 2024-11, with the labels that each got.

#7313 Remove prefixing releaseName with 'dokku-' in UninstallChart and GetValues calls in scheduler-k3s/triggers.go
  plugins/scheduler-k3s/triggers.go
Labels: type: bug

#7322 Add debugging information to brew bump-formula-pr
  .github/workflows/release.yml
Labels: type: enhancement

#7321 Allow nginx commands when the scheduler is set to null
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
Labels: type: bug, plugin: nginx

#7323 Correct errors in brew doctor output when making a formula release
  .github/workflows/release.yml
Labels: type: bug

#7328 Execute one-off commands with DOKKU_APP_SHELL as the initial command under the k3s scheduler
  plugins/app-json/functions.go
  plugins/app-json/triggers.go
  plugins/common/common.go
  plugins/scheduler-k3s/triggers.go
Labels: type: bug

#7330 Disable stdio buffering so log coloring happens normally when fetching logs for k3s-scheduler managed apps
  plugins/logs/subcommands.go
Labels: type: bug

#7331 Output logs for completed containers launched by the k3s scheduler
  plugins/common/log.go
  plugins/scheduler-k3s/functions.go
  plugins/scheduler-k3s/k8s.go
  plugins/scheduler-k3s/triggers.go
Labels: type: bug

#7332 Drop the pod name from stdout output when creating one-off containers under the k3s scheduler
  plugins/scheduler-k3s/triggers.go
Labels: type: bug

#7324 Correctly pull the deployment id from an app's helm values when executing dokku run under the k3s scheduler
  plugins/scheduler-k3s/template.go
  plugins/scheduler-k3s/templates/chart/cron-job.yaml
  plugins/scheduler-k3s/templates/chart/deployment.yaml
  plugins/scheduler-k3s/templates/chart/image-pull-secret.yaml
  plugins/scheduler-k3s/templates/chart/keda-scaled-object.yaml
  plugins/scheduler-k3s/templates/chart/keda-secret.yaml
  plugins/scheduler-k3s/templates/chart/keda-trigger-authentication.yaml
  plugins/scheduler-k3s/templates/chart/secret.yaml
  plugins/scheduler-k3s/triggers.go
  tests/unit/scheduler-k3s-2.bats
Labels: type: bug, plugin: scheduler-k3s

#7353 Add missing export DOKKU_LIB_HOST_ROOT when running dokku in container
  docker/etc/my_init.d/10_dokku_init
Labels: type: bug

#7355 Add support for http-based scaling when deploying on the k3s scheduler
  docs/deployment/schedulers/k3s.md
  plugins/scheduler-k3s/Makefile
  plugins/scheduler-k3s/functions.go
  plugins/scheduler-k3s/helm.go
  plugins/scheduler-k3s/scheduler_k3s.go
  plugins/scheduler-k3s/src/commands/commands.go
  plugins/scheduler-k3s/src/subcommands/subcommands.go
  plugins/scheduler-k3s/subcommands.go
  plugins/scheduler-k3s/template.go
  plugins/scheduler-k3s/templates/chart/ingress.yaml
  plugins/scheduler-k3s/templates/chart/keda-http-scaled-object.yaml
  plugins/scheduler-k3s/templates/chart/keda-interceptor-proxy-service.yaml
  plugins/scheduler-k3s/templates/chart/keda-scaled-object.yaml
  plugins/scheduler-k3s/templates/helm-config/keda-add-ons-http.yaml
  plugins/scheduler-k3s/triggers.go
  tests/unit/git_3.bats
Labels: type: enhancement, plugin: scheduler-k3s

#7361 Allow autoscaling config to have zero min replicas
  plugins/scheduler-k3s/template.go
Labels: type: bug
