Repository dokku/dokku, pull requests merged in 2024-10, with the labels that each got.

#7240 Update testing docs to specify that CI is performed on Ubuntu Noble
  docs/development/testing.md
Labels: type: documentation

#7241 Clarify phase utilization in docker-options docs
  docs/advanced-usage/docker-options.md
Labels: type: documentation

#7255 Do not attempt to expose the same mapped port more than once
  plugins/scheduler-docker-local/bin/scheduler-deploy-process-container
Labels: type: bug, plugin: scheduler-docker-local

#7269 Add support for various timeout-related functions to nginx, openresty and k3s plugins
  docs/networking/proxies/nginx.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/nginx-vhosts/internal-functions
  plugins/nginx-vhosts/nginx_vhosts.go
  plugins/nginx-vhosts/src/nginx-property/nginx-property.go
  plugins/nginx-vhosts/subcommands/set
  plugins/nginx-vhosts/templates/nginx.conf.sigil
  plugins/openresty-vhosts/command-functions
  plugins/openresty-vhosts/docker-args-process-deploy
  plugins/openresty-vhosts/internal-functions
  plugins/openresty-vhosts/subcommands/set
  plugins/scheduler-k3s/functions.go
Labels: type: enhancement, plugin: nginx, plugin: openresty, plugin: scheduler-k3s

#7271 Add support for non-local nginx implementations
  docs/development/plugin-triggers.md
  plugins/nginx-vhosts/functions
  plugins/scheduler-k3s/Makefile
  plugins/scheduler-k3s/functions.go
  plugins/scheduler-k3s/k8s.go
  plugins/scheduler-k3s/src/triggers/triggers.go
  plugins/scheduler-k3s/triggers.go
Labels: type: enhancement, plugin: nginx, plugin: scheduler-k3s

#7278 Allow usage of newer nginx.conf.sigil on older versions of dokku
  plugins/nginx-vhosts/templates/nginx.conf.sigil
Labels: type: enhancement, plugin: nginx

#7279 Allow exit code 2 when waiting for cloud-init to complete
  contrib/images/digitalocean/packer.pkr.hcl
Labels: type: bug

#7283 Force `docker builder prune` to skip confirmation
  plugins/builder/install-builder-prune
Labels: type: bug

#7285 Ensure builder pruning works when running under docker
  docker/etc/cron.d/docker-builder-prune
Labels: type: bug

#7284 Use correct name for scheduler-proxy-logs trigger
  plugins/nginx-vhosts/functions
  plugins/scheduler-k3s/Makefile
Labels: type: bug

#7286 Install netcat-traditional in 24.04 image
  contrib/images/digitalocean/in_parts/012-dokku-packages
Labels: type: bug

#7293 Strop non-numeric characters from certain ingress-nginx annotation values
  plugins/scheduler-k3s/functions.go
Labels: type: bug, plugin: scheduler-k3s

#7294 Tail the correct container in the ingress-nginx pod
  plugins/scheduler-k3s/triggers.go
Labels: type: bug, plugin: scheduler-k3s

#7295 Respect the exit code and pass flags correctly when tailing nginx logs on k3s
  plugins/nginx-vhosts/functions
  plugins/scheduler-k3s/triggers.go
Labels: type: bug

#7296 Implement nginx:show-config for k3s plugin
  docs/deployment/schedulers/k3s.md
  plugins/nginx-vhosts/command-functions
  plugins/nginx-vhosts/functions
  plugins/scheduler-k3s/Makefile
  plugins/scheduler-k3s/k8s.go
  plugins/scheduler-k3s/src/triggers/triggers.go
  plugins/scheduler-k3s/triggers.go
Labels: type: enhancement

#7297 Document a required ps:restart in order to apply annotations, labels, and nginx properties
  docs/deployment/schedulers/k3s.md
Labels: type: documentation
