Repository dokku/dokku, pull requests merged in 2025-02, with the labels that each got.

#7502 Ensure all report subcommands exit 0 when there is no app
  plugins/app-json/subcommands.go
  plugins/apps/subcommands.go
  plugins/builder/subcommands.go
  plugins/buildpacks/subcommands.go
  plugins/common/common.go
  plugins/common/functions.go
  plugins/cron/subcommands.go
  plugins/logs/subcommands.go
  plugins/network/subcommands.go
  plugins/ports/subcommands.go
  plugins/proxy/subcommands.go
  plugins/ps/subcommands.go
  plugins/registry/subcommands.go
  plugins/resource/subcommands.go
  plugins/scheduler-k3s/subcommands.go
  plugins/scheduler/subcommands.go
  tests/unit/report.bats
Labels: type: bug

#7527 Add swapoff to commands when creating or updating swap space
  docs/getting-started/advanced-installation.md
Labels: type: documentation

#7530 Finish sentence in docker-options documentation
  docs/advanced-usage/docker-options.md
Labels: type: documentation

#7542 Include troubleshooting details about app A being served when app B was expected due to in-app SSL redirects
  docs/getting-started/troubleshooting.md
Labels: type: documentation

#7545 feat: delegate authorized_keys file validation to sshcommand
  contrib/dependencies.json
  plugins/ssh-keys/subcommands/list
Labels: type: enhancement, plugin: ssh-keys
