Repository dokku/dokku, pull requests merged in 2025-08, with the labels that each got.

#7843 Bump go modules
  HISTORY.md
  contrib/images/digitalocean/in_parts/100-image-check
  contrib/release-dokku
  plugins/app-json/go.mod
  plugins/app-json/go.sum
  plugins/apps/go.mod
  plugins/apps/go.sum
  plugins/builder/go.mod
  plugins/builder/go.sum
  plugins/buildpacks/go.mod
  plugins/buildpacks/go.sum
  plugins/config/go.mod
  plugins/config/go.sum
  plugins/cron/go.mod
  plugins/cron/go.sum
  plugins/docker-options/go.mod
  plugins/docker-options/go.sum
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/network/go.mod
  plugins/network/go.sum
  plugins/nginx-vhosts/go.mod
  plugins/nginx-vhosts/go.sum
  plugins/ports/go.mod
  plugins/ports/go.sum
  plugins/proxy/go.mod
  plugins/proxy/go.sum
  plugins/ps/go.mod
  plugins/ps/go.sum
  plugins/registry/go.mod
  plugins/registry/go.sum
  plugins/repo/go.mod
  plugins/repo/go.sum
  plugins/resource/go.mod
  plugins/resource/go.sum
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-docker-local/go.sum
  plugins/scheduler-k3s/go.mod
  plugins/scheduler-k3s/go.sum
  plugins/scheduler/go.mod
  plugins/scheduler/go.sum
Labels: type: dependencies

#7841 Fix handling of equals sign in vector sink values
  go.work
  plugins/app-json/go.mod
  plugins/apps/go.mod
  plugins/builder/go.mod
  plugins/buildpacks/go.mod
  plugins/common/go.mod
  plugins/config/go.mod
  plugins/cron/go.mod
  plugins/docker-options/go.mod
  plugins/logs/go.mod
  plugins/logs/go.sum
  plugins/logs/logs.go
  plugins/network/go.mod
  plugins/nginx-vhosts/go.mod
  plugins/ports/go.mod
  plugins/proxy/go.mod
  plugins/ps/go.mod
  plugins/registry/go.mod
  plugins/repo/go.mod
  plugins/resource/go.mod
  plugins/scheduler-docker-local/go.mod
  plugins/scheduler-k3s/go.mod
  plugins/scheduler-k3s/go.sum
  plugins/scheduler/go.mod
  tests/unit/logs.bats
Labels: type: bug, needs: tests, plugin: logs

#7845 Use the official github actions arm64 runner
  .github/workflows/ci.yml
Labels: type: tests
