Repository dokku/dokku, pull requests merged in 2025-03, with the labels that each got.

#7572 Add support for setting shm-size for kubernetes deployments
  docs/deployment/schedulers/k3s.md
  plugins/scheduler-k3s/functions.go
  plugins/scheduler-k3s/report.go
  plugins/scheduler-k3s/scheduler_k3s.go
  plugins/scheduler-k3s/template.go
  plugins/scheduler-k3s/templates/chart/deployment.yaml
  plugins/scheduler-k3s/triggers.go
  tests/unit/scheduler-k3s-2.bats
Labels: type: enhancement

#7574 fix: do not write VHOST file if the DOKKU_ROOT directory does not exist
  plugins/00_dokku-standard/install
Labels: type: bug

#7575 Restore the git head ref when running repo:gc
  plugins/repo/repo.go
  plugins/repo/subcommands.go
Labels: type: bug, merge-level: patch

#7580 Do not set network flag when building dockerfile images
  plugins/network/src/triggers/triggers.go
  plugins/network/triggers.go
Labels: type: bug, plugin: network

#7586 Remove `--` from `--git-url` in plugin installation docs
  docs/advanced-usage/plugin-management.md
Labels: type: documentation

#7583 Send Host header when running container checks in docker-local
  plugins/scheduler-docker-local/check-deploy
Labels: type: enhancement, merge-level: patch, plugin: checks

#7581 Allow --volume flags to be passed to pack at buildtime
  plugins/builder-pack/builder-build
Labels: type: enhancement, merge-level: patch

#7584 Install all builder binaries in Dokku docker image
  Dockerfile
  docker/etc/sudoers.d/dokku-docker
  docker/usr/local/bin/lambda-builder
  docker/usr/local/bin/nixpacks
Labels: type: bug, merge-level: patch

#7587 Correctly name paketo chown option
  docs/advanced-usage/persistent-storage.md
  plugins/storage/internal-functions
  tests/unit/storage.bats
Labels: type: bug, merge-level: patch

#7596 Drop compromisde tj-actions/changed-files from Ci
  .github/workflows/lint.yml
Labels: security
