Repository dokku/dokku, pull requests merged in 2025-04, with the labels that each got.

#7648 feat: add ability to ship k3s container logs via vector
  docs/deployment/schedulers/k3s.md
  plugins/logs/functions.go
  plugins/logs/logs.go
  plugins/logs/set.go
  plugins/scheduler-k3s/functions.go
  plugins/scheduler-k3s/go.mod
  plugins/scheduler-k3s/go.sum
  plugins/scheduler-k3s/scheduler_k3s.go
  plugins/scheduler-k3s/templates/helm-config/vector.yaml
Labels: type: enhancement, merge-level: patch, plugin: scheduler-k3s

#7652 docs: use a cid-file in the plugin example
  docs/development/plugin-triggers.md
Labels: type: documentation

#7606 fix: bump dokku version in main.bicep when bumping azure versions
  .github/commands/bump-azure
Labels: type: bug

#7653 chore: bump docker-container-healthchecker from 0.11.0 to 0.11.5
  contrib/dependencies.json
Labels: dependencies

#7677 Add continuous integration example for woodpecker ci
  docs/deployment/continuous-integration/generic.md
  docs/deployment/continuous-integration/woodpecker-ci.md
  docs/template.html
Labels: type: documentation

#7678 Revert "fix: update CID count in ps tests"
  tests/unit/ps-general-1.bats
Labels: type: tests

#7686 Untap aws/tap to correct issues in formula release
  .github/workflows/release.yml
Labels: type: bug

#7687 Fix cron key in app.json docs
  docs/appendices/file-formats/app-json.md
Labels: type: documentation
